version: '3.4'
networks:
  api:
    driver: bridge

services:
  webapi:
    container_name: WebApi
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      DB_CONNECTION_STRING: "Server=mssql;Database=Library;User ID=sa;Password=Sa_password!;"
    networks:
      - api
    ports:
      - "5000:443"
      - "5001:80"
  mssql:
    container_name: MSSQL
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Sa_password!"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - api