version: '3.4'
networks:
  api:
    driver: bridge

services:
  webapi:
    container_name: WebApi
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      DB_CONNECTION_STRING: "Server=mssql;Database=Library;User ID=sa;Password=Sa_password!;"
    networks:
      - api
    ports:
      - "5000:443"
      - "5001:80"
  mssql:
    container_name: MSSQL
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Sa_password!"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - api
  elasticsearch:
    container_name: ElasticSearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g
    ulimits:
      memlock:
        hard: -1
        soft: -1
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    networks:
      - api
  kibana:
    container_name: Kibana
    image: docker.elastic.co/kibana/kibana:7.10.0
    depends_on:
        elasticsearch:
            condition: service_healthy
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status
    ports:
      - "5601:5601"
    networks:
      - api
  apm-server:
    container_name: ApmServer
    image: docker.elastic.co/apm/apm-server:7.10.0
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    command: >
       apm-server -e
         -E apm-server.rum.enabled=true
         -E setup.kibana.host=kibana:5601
         -E setup.template.settings.index.number_of_replicas=0
         -E apm-server.kibana.enabled=true
         -E apm-server.kibana.host=kibana:5601
         -E output.elasticsearch.hosts=["elasticsearch:9200"]
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/
    ports:
    - 8200:8200
    networks:
    - api

volumes:
  esdata:
     driver: local