version: '3.4'
networks:
  api:
    driver: bridge

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: ThreadInMotionInterviewTask/Dockerfile
    networks:
      - api
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "sapassword!"
        ACCEPT_EULA: "Y"
    networks:
      - api
