// <auto-generated />
using System;
using DataAccess.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20210116165015_BooksAndMembers")]
    partial class BooksAndMembers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Entities.Book", b =>
                {
                    b.Property<string>("IsbnId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("IsbnId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            IsbnId = "4053208708088",
                            Author = "Mood Ruff",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9708952959520",
                            Author = "George Michael",
                            BookName = "Screamo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3637449606108",
                            Author = "Men Without Hats",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7120375065295",
                            Author = "L'Étranger",
                            BookName = "Caribbean Blues",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7626453958416",
                            Author = "Garth Brooks",
                            BookName = "Screamo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2933456053539",
                            Author = "DJ Jazzy Jeff and the Fresh Prince",
                            BookName = "Easy Listening",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7066015512041",
                            Author = "MCJ & Cool G",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6524093145904",
                            Author = "Mir",
                            BookName = "Kansas City Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9074430958949",
                            Author = "Moneyshot",
                            BookName = "Hard Easy Listening",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6501338053780",
                            Author = "Bruce Springsteen",
                            BookName = "Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5489695844560",
                            Author = "The Moffatts",
                            BookName = "Classical",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7494505052909",
                            Author = "Love Kills",
                            BookName = "Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3819329703987",
                            Author = "Matthew Good Band",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1762948941743",
                            Author = "Mystery",
                            BookName = "Jazzy Pop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0819247943531",
                            Author = "Lola Dutronic",
                            BookName = "Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6903769515914",
                            Author = "The Lemon Bucket Orkestra",
                            BookName = "Acid Folk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5699856182877",
                            Author = "AC/DC",
                            BookName = "Modern Pop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4157326349025",
                            Author = "Main Source",
                            BookName = "Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0653652554570",
                            Author = "My Darkest Days",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4348655291203",
                            Author = "Mother Mother",
                            BookName = "Jazzy Children's",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2135349001373",
                            Author = "The Mynah Birds",
                            BookName = "Avant-Garde Screamo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0119074835483",
                            Author = "Love and Sas",
                            BookName = "Glam Doo-Wop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7960990752169",
                            Author = "Means",
                            BookName = "Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2852178166462",
                            Author = "Mobile",
                            BookName = "Caribbean Easy Listening",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7504066795806",
                            Author = "Julio Iglesias",
                            BookName = "Folk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6081480646432",
                            Author = "Mir",
                            BookName = "Children's",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1593465873565",
                            Author = "Lioness",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9162730330865",
                            Author = "Barbra Streisand",
                            BookName = "Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0674489792946",
                            Author = "LMDS",
                            BookName = "Screamo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2791217547910",
                            Author = "Magneta Lane",
                            BookName = "Classic R&B",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2826594898000",
                            Author = "The Carpenters",
                            BookName = "Jazzy Doo-Wop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5388426214145",
                            Author = "Mahogany Rush",
                            BookName = "Blues",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4152609393947",
                            Author = "Library Voices",
                            BookName = "Acid Classical",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4624103831040",
                            Author = "Michael Jackson",
                            BookName = "Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7242444566973",
                            Author = "Mes Aïeux",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3278432379304",
                            Author = "The Rolling Stones",
                            BookName = "Asian Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0126780640414",
                            Author = "Mes Aïeux",
                            BookName = "Glam House",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0171611213274",
                            Author = "Linda Ronstadt",
                            BookName = "Electronic Dance",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6479510271270",
                            Author = "Matthew Good Band",
                            BookName = "Fresh Easy Listening",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6806688629575",
                            Author = "The McDades",
                            BookName = "Grunge",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6754085902991",
                            Author = "The Beatles",
                            BookName = "Free Grunge",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0676843280357",
                            Author = "U2",
                            BookName = "House",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8304921484399",
                            Author = "My Darkest Days",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4586629051371",
                            Author = "Farm Fresh",
                            BookName = "Doo-Wop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8616632472025",
                            Author = "Luke & The Apostles",
                            BookName = "Electronic Screamo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9082105557417",
                            Author = "Last Man Out",
                            BookName = "Glam R&B",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0769646655913",
                            Author = "MacLean & MacLean",
                            BookName = "Children's",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3092429728206",
                            Author = "Kiss",
                            BookName = "Blues",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2783084748903",
                            Author = "Linda Ronstadt",
                            BookName = "Folk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7490497757676",
                            Author = "MCJ & Cool G",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4685266556404",
                            Author = "Mare",
                            BookName = "Hard Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4731175461971",
                            Author = "The Manvils",
                            BookName = "Fresh R&B",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4640707655725",
                            Author = "McKenna Mendelson Mainline",
                            BookName = "Acid Easy Listening",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9736771776761",
                            Author = "Moxy Früvous",
                            BookName = "Pop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4274109223306",
                            Author = "The McDades",
                            BookName = "Asian Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1196572045858",
                            Author = "Love Inc.",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9010370380604",
                            Author = "Lost & Profound",
                            BookName = "Children's",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8047699612898",
                            Author = "Moneen",
                            BookName = "Electronic Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6878726442741",
                            Author = "Manic Drive",
                            BookName = "Doo-Wop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8807391485237",
                            Author = "Leahy",
                            BookName = "Fresh Screamo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8602428353227",
                            Author = "The Beatles",
                            BookName = "Doo-Wop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5165703354430",
                            Author = "U2",
                            BookName = "Asian Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3112051526210",
                            Author = "Eminem",
                            BookName = "Modern Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3545651584291",
                            Author = "The Marble Index",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0937171329033",
                            Author = "Liferuiner",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7363697803667",
                            Author = "The Meligrove Band",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0604343832214",
                            Author = "Machete Avenue",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6457644046201",
                            Author = "The Manvils",
                            BookName = "Electronic Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1782912548024",
                            Author = "Red Hot Chili Peppers",
                            BookName = "Screamo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4803233737480",
                            Author = "Motion Ensemble",
                            BookName = "Dance",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4039417048753",
                            Author = "Merlin",
                            BookName = "Acid Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2790673142857",
                            Author = "Love and Sas",
                            BookName = "Modern R&B",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4940224251008",
                            Author = "Len",
                            BookName = "Screamo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1109392098248",
                            Author = "Maow",
                            BookName = "Asian Children's",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4856997561464",
                            Author = "Mother Mother",
                            BookName = "R&B",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8720923894270",
                            Author = "Mudmen",
                            BookName = "Electronic Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9076551524338",
                            Author = "Leigh Ashford",
                            BookName = "Modern Dance",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0636809874049",
                            Author = "Manic Drive",
                            BookName = "Free Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1497973867690",
                            Author = "Rihanna",
                            BookName = "Blues",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5684399411642",
                            Author = "Cher",
                            BookName = "Blues",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2574262163771",
                            Author = "Mes Aïeux",
                            BookName = "Jazzy Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5763464318612",
                            Author = "The Beatles",
                            BookName = "Free Easy Listening",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3642083755214",
                            Author = "Mystery Machine",
                            BookName = "Grunge",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0446410208523",
                            Author = "My Darkest Days",
                            BookName = "Funk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5368379164759",
                            Author = "Elvis Presley",
                            BookName = "Classic Classical",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5357857609282",
                            Author = "The Mark Inside",
                            BookName = "House",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8010146731672",
                            Author = "Paul McCartney",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1678255790439",
                            Author = "Van Halen",
                            BookName = "Fresh Blues",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7612422780986",
                            Author = "The Matadors",
                            BookName = "Folk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3308310694368",
                            Author = "Lola Dutronic",
                            BookName = "Jazzy Doo-Wop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1530480171953",
                            Author = "Pink Floyd",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9341509200767",
                            Author = "The Doors",
                            BookName = "Electronic Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0555312943785",
                            Author = "Major Maker",
                            BookName = "Pop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4934546959286",
                            Author = "Moist",
                            BookName = "House",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5466688449601",
                            Author = "The Mountains and the Trees",
                            BookName = "Blues",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8850800721815",
                            Author = "Mandala",
                            BookName = "Brazillian Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4827219927399",
                            Author = "Last Man Out",
                            BookName = "Caribbean Blues",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2021708073360",
                            Author = "DJ Jazzy Jeff and the Fresh Prince",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0911885895591",
                            Author = "Masochistic Religion",
                            BookName = "Screamo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8515362841611",
                            Author = "Lillix",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5740199898455",
                            Author = "Mare",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1574430782965",
                            Author = "MSTRKRFT",
                            BookName = "Classic Children's",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8571935353435",
                            Author = "Lost & Profound",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5242279184675",
                            Author = "Leigh Ashford",
                            BookName = "Caribbean Screamo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0713518882175",
                            Author = "Rihanna",
                            BookName = "Dance",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9157011586801",
                            Author = "Santana",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7053379384215",
                            Author = "Mahogany Rush",
                            BookName = "Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0793743730731",
                            Author = "Merlin",
                            BookName = "R&B",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2142212388549",
                            Author = "Santana",
                            BookName = "Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2815603502290",
                            Author = "Guns N' Roses",
                            BookName = "Classic Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9382428694773",
                            Author = "Rod Stewart",
                            BookName = "Funk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5636008679806",
                            Author = "Phil Collins",
                            BookName = "Blues",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3812153918461",
                            Author = "Lost & Profound",
                            BookName = "Fresh Easy Listening",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8456765204352",
                            Author = "Farm Fresh",
                            BookName = "Classical",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3495567494718",
                            Author = "Lightning Dust",
                            BookName = "Screamo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0101392207868",
                            Author = "Memphis",
                            BookName = "Folk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8786047772468",
                            Author = "Maow",
                            BookName = "Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9928069490939",
                            Author = "Loco Locass",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5439710592785",
                            Author = "Love Inc.",
                            BookName = "Electronic Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2841741893003",
                            Author = "Bruce Springsteen",
                            BookName = "Classical",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6615979245247",
                            Author = "Martyr",
                            BookName = "Free R&B",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6188516215028",
                            Author = "Mercey Brothers",
                            BookName = "Blues",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6107649438467",
                            Author = "ABBA",
                            BookName = "Classic Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5737020026910",
                            Author = "B'z",
                            BookName = "Classical",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0535181738780",
                            Author = "Moev",
                            BookName = "Easy Listening",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1960336021238",
                            Author = "Lightning Dust",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9497788372324",
                            Author = "Tina Turner",
                            BookName = "Free Blues",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7268105464975",
                            Author = "Maow",
                            BookName = "Brazillian Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2905131821899",
                            Author = "Lioness",
                            BookName = "Glam Screamo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3268605012903",
                            Author = "Garth Brooks",
                            BookName = "Brazillian Doo-Wop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1156142140123",
                            Author = "Lee Harvey Osmond",
                            BookName = "Fresh Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4317281624230",
                            Author = "Means",
                            BookName = "Folk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6987342151711",
                            Author = "Neil Diamond",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0245039199332",
                            Author = "Merryweather",
                            BookName = "Folk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7206617686439",
                            Author = "Moneyshot",
                            BookName = "Hard Screamo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8262269554058",
                            Author = "Mother Mother",
                            BookName = "R&B",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4453957138429",
                            Author = "Mother Mother",
                            BookName = "Classic Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5662232743791",
                            Author = "Library Voices",
                            BookName = "Glam Folk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6995329499600",
                            Author = "Elvis Presley",
                            BookName = "Easy Listening",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3473785751211",
                            Author = "Liferuiner",
                            BookName = "Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5566906398319",
                            Author = "Celine Dion",
                            BookName = "Folk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4478821174195",
                            Author = "Fleetwood Mac",
                            BookName = "Acid Easy Listening",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6798461575143",
                            Author = "Loco Locass",
                            BookName = "Funk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2059257451949",
                            Author = "Gloria Estefan",
                            BookName = "Brazillian Dance",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1188300172847",
                            Author = "Main Source",
                            BookName = "Glam Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3156909665398",
                            Author = "Love Inc.",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2791783455559",
                            Author = "Barry Manilow",
                            BookName = "Pop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9360965912686",
                            Author = "Mountain City Four",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8701417637820",
                            Author = "Bruce Springsteen",
                            BookName = "Avant-Garde Doo-Wop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2627724414986",
                            Author = "Moev",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7327181122599",
                            Author = "Men Without Hats",
                            BookName = "Free R&B",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2161578609712",
                            Author = "Van Halen",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3844415653829",
                            Author = "The Look People",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5332562175842",
                            Author = "The McDades",
                            BookName = "Easy Listening",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9161811769616",
                            Author = "Genesis",
                            BookName = "Jazzy Folk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6814101856680",
                            Author = "Eagles",
                            BookName = "Classic Screamo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2729219517750",
                            Author = "Loverboy",
                            BookName = "House",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0097333499778",
                            Author = "Paul McCartney",
                            BookName = "African Folk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1969525619148",
                            Author = "Mecca Normal",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6015601034189",
                            Author = "Metallica",
                            BookName = "Electronic Doo-Wop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6921651387729",
                            Author = "The Lincolns",
                            BookName = "Fresh Funk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7047692092493",
                            Author = "Leahy",
                            BookName = "Classic Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5151040082085",
                            Author = "Frank Sinatra",
                            BookName = "Brazillian Screamo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6136035548898",
                            Author = "The Moffatts",
                            BookName = "Screamo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8921889535419",
                            Author = "Metalwood",
                            BookName = "Classic House",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2327575243796",
                            Author = "Billy Joel",
                            BookName = "Easy Listening",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5911084701349",
                            Author = "Max Webster",
                            BookName = "Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0829562892381",
                            Author = "Luther Wright and the Wrongs",
                            BookName = "Pop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8512565691165",
                            Author = "Metalwood",
                            BookName = "Hard Pop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2495726113912",
                            Author = "Loco Locass",
                            BookName = "Modern Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2909863242692",
                            Author = "Chicago",
                            BookName = "Caribbean Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0386243201930",
                            Author = "MacLean & MacLean",
                            BookName = "Children's",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0195178164592",
                            Author = "Library Voices",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9228353014826",
                            Author = "Van Halen",
                            BookName = "Folk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4537263667936",
                            Author = "Billy Joel",
                            BookName = "Electronic Funk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9399576244305",
                            Author = "Queen",
                            BookName = "House",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6652482813138",
                            Author = "Lillix",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1310820159771",
                            Author = "AC/DC",
                            BookName = "Avant-Garde Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1811158027315",
                            Author = "Bruce Springsteen",
                            BookName = "Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4640710246634",
                            Author = "AC/DC",
                            BookName = "Brazillian Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6430970738932",
                            Author = "Miriodor",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7399240632891",
                            Author = "Led Zeppelin",
                            BookName = "Electronic Grunge",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5829116000407",
                            Author = "Me Mom & Morgentaler",
                            BookName = "Kansas City House",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7539835580166",
                            Author = "MonkeyJunk",
                            BookName = "Classic Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3203842063557",
                            Author = "Kiss",
                            BookName = "Screamo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6256991703664",
                            Author = "Letters to Elora",
                            BookName = "Grunge",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7735294143653",
                            Author = "The Beatles",
                            BookName = "Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8917198149122",
                            Author = "Local Rabbits",
                            BookName = "African Blues",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8345635602969",
                            Author = "Lillix",
                            BookName = "Jazzy Easy Listening",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7654944003012",
                            Author = "Barry Manilow",
                            BookName = "Hard House",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2795488209561",
                            Author = "Moneyshot",
                            BookName = "Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1619041811904",
                            Author = "MacLean & MacLean",
                            BookName = "Avant-Garde Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0955145297895",
                            Author = "Madonna",
                            BookName = "Fresh Screamo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8242156638664",
                            Author = "Moneyshot",
                            BookName = "Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3814552536735",
                            Author = "Moneyshot",
                            BookName = "Classical",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5781632479079",
                            Author = "Linda Ronstadt",
                            BookName = "Jazzy Easy Listening",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6590219265363",
                            Author = "Magneta Lane",
                            BookName = "Screamo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7924854199497",
                            Author = "The Rolling Stones",
                            BookName = "R&B",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0399796089783",
                            Author = "AC/DC",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6123153102304",
                            Author = "The Mark Inside",
                            BookName = "Jazz",
                            Count = 3
                        });
                });

            modelBuilder.Entity("Entities.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            BirthDate = new DateTime(1968, 4, 7, 12, 29, 12, 0, DateTimeKind.Unspecified),
                            EmailAddress = "saramackenzie@libra.ry",
                            FirstName = "Sara",
                            HomeAddress = "129 Norfolk Street ",
                            LastName = "MacKenzie",
                            Password = "year",
                            PhoneNumber = "(466) 555-5895",
                            RegistrationDate = new DateTime(2018, 7, 7, 19, 50, 15, 423, DateTimeKind.Local).AddTicks(7177),
                            Username = "saramackenzie"
                        },
                        new
                        {
                            MemberId = 2,
                            BirthDate = new DateTime(1939, 2, 20, 7, 14, 23, 0, DateTimeKind.Unspecified),
                            EmailAddress = "josefoster@libra.ry",
                            FirstName = "Jose",
                            HomeAddress = "991 Atkins Avenue ",
                            LastName = "Foster",
                            Password = "place",
                            PhoneNumber = "(541) 471-2782",
                            RegistrationDate = new DateTime(2018, 10, 25, 19, 50, 15, 423, DateTimeKind.Local).AddTicks(9674),
                            Username = "josefoster"
                        },
                        new
                        {
                            MemberId = 3,
                            BirthDate = new DateTime(1918, 5, 3, 2, 12, 59, 0, DateTimeKind.Unspecified),
                            EmailAddress = "coleıginla@libra.ry",
                            FirstName = "Cole",
                            HomeAddress = "4763 Vanderbilt Street ",
                            LastName = "Iginla",
                            Password = "narwhal",
                            PhoneNumber = "(469) 579-1947",
                            RegistrationDate = new DateTime(2020, 1, 23, 19, 50, 15, 424, DateTimeKind.Local).AddTicks(201),
                            Username = "coleıginla"
                        },
                        new
                        {
                            MemberId = 4,
                            BirthDate = new DateTime(1944, 7, 5, 23, 26, 28, 0, DateTimeKind.Unspecified),
                            EmailAddress = "evelyncarter@libra.ry",
                            FirstName = "Evelyn",
                            HomeAddress = "7998 Hart Street ",
                            LastName = "Carter",
                            Password = "tofu",
                            PhoneNumber = "(435) 220-7333",
                            RegistrationDate = new DateTime(2019, 2, 12, 19, 50, 15, 424, DateTimeKind.Local).AddTicks(778),
                            Username = "evelyncarter"
                        },
                        new
                        {
                            MemberId = 5,
                            BirthDate = new DateTime(1902, 8, 10, 14, 11, 15, 0, DateTimeKind.Unspecified),
                            EmailAddress = "kaylamartinez@libra.ry",
                            FirstName = "Kayla",
                            HomeAddress = "5950 28th Street ",
                            LastName = "Martinez",
                            Password = "Iphone",
                            PhoneNumber = "(230) 670-1474",
                            RegistrationDate = new DateTime(2019, 11, 12, 19, 50, 15, 424, DateTimeKind.Local).AddTicks(1254),
                            Username = "kaylamartinez"
                        },
                        new
                        {
                            MemberId = 6,
                            BirthDate = new DateTime(1971, 9, 17, 0, 5, 14, 0, DateTimeKind.Unspecified),
                            EmailAddress = "shelbymorris@libra.ry",
                            FirstName = "Shelby",
                            HomeAddress = "6935 Paerdegat 5th Street ",
                            LastName = "Morris",
                            Password = "Lomo",
                            PhoneNumber = "(446) 316-3679",
                            RegistrationDate = new DateTime(2018, 7, 7, 19, 50, 15, 424, DateTimeKind.Local).AddTicks(1721),
                            Username = "shelbymorris"
                        },
                        new
                        {
                            MemberId = 7,
                            BirthDate = new DateTime(2016, 2, 8, 10, 15, 27, 0, DateTimeKind.Unspecified),
                            EmailAddress = "victorramirez@libra.ry",
                            FirstName = "Victor",
                            HomeAddress = "9105 Paerdegat 2nd Street ",
                            LastName = "Ramirez",
                            Password = "on",
                            PhoneNumber = "(373) 690-1248",
                            RegistrationDate = new DateTime(2020, 6, 26, 19, 50, 15, 424, DateTimeKind.Local).AddTicks(2178),
                            Username = "victorramirez"
                        },
                        new
                        {
                            MemberId = 8,
                            BirthDate = new DateTime(1948, 10, 3, 11, 32, 3, 0, DateTimeKind.Unspecified),
                            EmailAddress = "laurenadams@libra.ry",
                            FirstName = "Lauren",
                            HomeAddress = "1649 Hull Street ",
                            LastName = "Adams",
                            Password = "bicycle",
                            PhoneNumber = "(608) 416-2123",
                            RegistrationDate = new DateTime(2018, 10, 30, 19, 50, 15, 424, DateTimeKind.Local).AddTicks(2698),
                            Username = "laurenadams"
                        },
                        new
                        {
                            MemberId = 9,
                            BirthDate = new DateTime(1972, 10, 2, 2, 7, 39, 0, DateTimeKind.Unspecified),
                            EmailAddress = "bryanmartinez@libra.ry",
                            FirstName = "Bryan",
                            HomeAddress = "3470 Ocean Court ",
                            LastName = "Martinez",
                            Password = "way",
                            PhoneNumber = "(214) 563-1547",
                            RegistrationDate = new DateTime(2019, 2, 8, 19, 50, 15, 424, DateTimeKind.Local).AddTicks(3166),
                            Username = "bryanmartinez"
                        },
                        new
                        {
                            MemberId = 10,
                            BirthDate = new DateTime(2011, 12, 12, 18, 35, 17, 0, DateTimeKind.Unspecified),
                            EmailAddress = "samuelpearson@libra.ry",
                            FirstName = "Samuel",
                            HomeAddress = "9573 Neptune Avenue ",
                            LastName = "Pearson",
                            Password = "pork",
                            PhoneNumber = "(685) 673-8958",
                            RegistrationDate = new DateTime(2018, 12, 31, 19, 50, 15, 424, DateTimeKind.Local).AddTicks(3646),
                            Username = "samuelpearson"
                        },
                        new
                        {
                            MemberId = 11,
                            BirthDate = new DateTime(1907, 5, 5, 10, 23, 37, 0, DateTimeKind.Unspecified),
                            EmailAddress = "lilliansmith@libra.ry",
                            FirstName = "Lillian",
                            HomeAddress = "5792 Elliott Place ",
                            LastName = "Smith",
                            Password = "pickled",
                            PhoneNumber = "(453) 676-3153",
                            RegistrationDate = new DateTime(2018, 8, 30, 19, 50, 15, 424, DateTimeKind.Local).AddTicks(4080),
                            Username = "lilliansmith"
                        },
                        new
                        {
                            MemberId = 12,
                            BirthDate = new DateTime(1962, 12, 4, 1, 27, 36, 0, DateTimeKind.Unspecified),
                            EmailAddress = "christopherwood@libra.ry",
                            FirstName = "Christopher",
                            HomeAddress = "8155 Tudor Terrace ",
                            LastName = "Wood",
                            Password = "pour-over",
                            PhoneNumber = "(487) 368-4205",
                            RegistrationDate = new DateTime(2019, 7, 3, 19, 50, 15, 424, DateTimeKind.Local).AddTicks(4565),
                            Username = "christopherwood"
                        },
                        new
                        {
                            MemberId = 13,
                            BirthDate = new DateTime(1908, 1, 14, 14, 21, 25, 0, DateTimeKind.Unspecified),
                            EmailAddress = "brandonhall@libra.ry",
                            FirstName = "Brandon",
                            HomeAddress = "8869 Kansas Place ",
                            LastName = "Hall",
                            Password = "truffaut",
                            PhoneNumber = "(519) 367-0346",
                            RegistrationDate = new DateTime(2019, 10, 5, 19, 50, 15, 424, DateTimeKind.Local).AddTicks(5042),
                            Username = "brandonhall"
                        },
                        new
                        {
                            MemberId = 14,
                            BirthDate = new DateTime(1983, 7, 2, 21, 43, 44, 0, DateTimeKind.Unspecified),
                            EmailAddress = "josephcoleman@libra.ry",
                            FirstName = "Joseph",
                            HomeAddress = "7966 Cranberry Street ",
                            LastName = "Coleman",
                            Password = "narwhal",
                            PhoneNumber = "(378) 277-3884",
                            RegistrationDate = new DateTime(2019, 2, 25, 19, 50, 15, 424, DateTimeKind.Local).AddTicks(5499),
                            Username = "josephcoleman"
                        },
                        new
                        {
                            MemberId = 15,
                            BirthDate = new DateTime(1940, 2, 27, 10, 46, 54, 0, DateTimeKind.Unspecified),
                            EmailAddress = "gabrielroberts@libra.ry",
                            FirstName = "Gabriel",
                            HomeAddress = "9557 Lancaster Avenue ",
                            LastName = "Roberts",
                            Password = "hella",
                            PhoneNumber = "(304) 357-1412",
                            RegistrationDate = new DateTime(2019, 3, 4, 19, 50, 15, 424, DateTimeKind.Local).AddTicks(5935),
                            Username = "gabrielroberts"
                        },
                        new
                        {
                            MemberId = 16,
                            BirthDate = new DateTime(1921, 4, 27, 8, 45, 58, 0, DateTimeKind.Unspecified),
                            EmailAddress = "oliviawilliams@libra.ry",
                            FirstName = "Olivia",
                            HomeAddress = "9724 Turnbull Avenue ",
                            LastName = "Williams",
                            Password = "forage",
                            PhoneNumber = "(355) 570-9072",
                            RegistrationDate = new DateTime(2018, 9, 18, 19, 50, 15, 424, DateTimeKind.Local).AddTicks(6433),
                            Username = "oliviawilliams"
                        },
                        new
                        {
                            MemberId = 17,
                            BirthDate = new DateTime(1918, 11, 13, 19, 15, 46, 0, DateTimeKind.Unspecified),
                            EmailAddress = "annaevans@libra.ry",
                            FirstName = "Anna",
                            HomeAddress = "8224 Pershing Loop ",
                            LastName = "Evans",
                            Password = "you",
                            PhoneNumber = "(457) 515-8617",
                            RegistrationDate = new DateTime(2019, 9, 7, 19, 50, 15, 424, DateTimeKind.Local).AddTicks(6911),
                            Username = "annaevans"
                        },
                        new
                        {
                            MemberId = 18,
                            BirthDate = new DateTime(1956, 9, 29, 2, 4, 23, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rileywatson@libra.ry",
                            FirstName = "Riley",
                            HomeAddress = "1187 Morgan Avenue ",
                            LastName = "Watson",
                            Password = "richardson",
                            PhoneNumber = "(391) 364-4306",
                            RegistrationDate = new DateTime(2020, 12, 8, 19, 50, 15, 424, DateTimeKind.Local).AddTicks(7388),
                            Username = "rileywatson"
                        },
                        new
                        {
                            MemberId = 19,
                            BirthDate = new DateTime(1960, 3, 6, 17, 55, 49, 0, DateTimeKind.Unspecified),
                            EmailAddress = "brycecollins@libra.ry",
                            FirstName = "Bryce",
                            HomeAddress = "950 Erskine Loop ",
                            LastName = "Collins",
                            Password = "womn",
                            PhoneNumber = "(399) 628-7979",
                            RegistrationDate = new DateTime(2018, 4, 30, 19, 50, 15, 424, DateTimeKind.Local).AddTicks(7820),
                            Username = "brycecollins"
                        },
                        new
                        {
                            MemberId = 20,
                            BirthDate = new DateTime(1937, 8, 18, 21, 45, 28, 0, DateTimeKind.Unspecified),
                            EmailAddress = "alyssaedwards@libra.ry",
                            FirstName = "Alyssa",
                            HomeAddress = "7954 Withers Street ",
                            LastName = "Edwards",
                            Password = "terry",
                            PhoneNumber = "(575) 780-9267",
                            RegistrationDate = new DateTime(2020, 6, 29, 19, 50, 15, 424, DateTimeKind.Local).AddTicks(8275),
                            Username = "alyssaedwards"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
