// <auto-generated />
using System;
using DataAccess.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20210116160035_BooksAndMembers")]
    partial class BooksAndMembers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Entities.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentHolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsbnId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Moev",
                            BookName = "Funk",
                            CurrentHolder = "pack",
                            IsbnId = "9557715328204"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "The MRQ",
                            BookName = "Pop",
                            CurrentHolder = "post-ironic",
                            IsbnId = "3973063283587"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Martha and the Muffins",
                            BookName = "Kansas City Pop",
                            CurrentHolder = "life",
                            IsbnId = "7393544068277"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Moist",
                            BookName = "Avant-Garde Easy Listening",
                            CurrentHolder = "skateboard",
                            IsbnId = "1159625929388"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Mes Aïeux",
                            BookName = "R&B",
                            CurrentHolder = "world",
                            IsbnId = "2377057360660"
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Cher",
                            BookName = "Dance",
                            CurrentHolder = "richardson",
                            IsbnId = "2338035768986"
                        },
                        new
                        {
                            BookId = 7,
                            Author = "Lotus Child",
                            BookName = "Fresh Funk",
                            CurrentHolder = "carles",
                            IsbnId = "5644342971800"
                        },
                        new
                        {
                            BookId = 8,
                            Author = "Chicago",
                            BookName = "African Funk",
                            CurrentHolder = "company",
                            IsbnId = "1657999787320"
                        },
                        new
                        {
                            BookId = 9,
                            Author = "Lightning Dust",
                            BookName = "Funk",
                            CurrentHolder = "seitan",
                            IsbnId = "4298578255948"
                        },
                        new
                        {
                            BookId = 10,
                            Author = "The Memories Attack",
                            BookName = "Hard Emo",
                            CurrentHolder = "batch",
                            IsbnId = "801044819318"
                        },
                        new
                        {
                            BookId = 11,
                            Author = "Mystery",
                            BookName = "Glam Jazz",
                            CurrentHolder = "womn",
                            IsbnId = "2016758109450"
                        },
                        new
                        {
                            BookId = 12,
                            Author = "LMDS",
                            BookName = "Funk",
                            CurrentHolder = "direct",
                            IsbnId = "7156382378729"
                        },
                        new
                        {
                            BookId = 13,
                            Author = "Eagles",
                            BookName = "Fresh Pop",
                            CurrentHolder = "government",
                            IsbnId = "7447160104032"
                        },
                        new
                        {
                            BookId = 14,
                            Author = "Moev",
                            BookName = "Jazz",
                            CurrentHolder = "haven't",
                            IsbnId = "8226705653698"
                        },
                        new
                        {
                            BookId = 15,
                            Author = "The Luyas",
                            BookName = "Funk",
                            CurrentHolder = "park",
                            IsbnId = "5233703379162"
                        },
                        new
                        {
                            BookId = 16,
                            Author = "Kate and Anna McGarrigle",
                            BookName = "Jazz",
                            CurrentHolder = "occupy",
                            IsbnId = "5551036016806"
                        },
                        new
                        {
                            BookId = 17,
                            Author = "Barry Manilow",
                            BookName = "Brazillian Children's",
                            CurrentHolder = "booth",
                            IsbnId = "5504994055025"
                        },
                        new
                        {
                            BookId = 18,
                            Author = "The Look People",
                            BookName = "Free Rock",
                            CurrentHolder = "Polaroid",
                            IsbnId = "8991747819349"
                        },
                        new
                        {
                            BookId = 19,
                            Author = "Madonna",
                            BookName = "Jazzy Jazz",
                            CurrentHolder = "organic",
                            IsbnId = "5385806427982"
                        },
                        new
                        {
                            BookId = 20,
                            Author = "AC/DC",
                            BookName = "Acid Rock",
                            CurrentHolder = "it",
                            IsbnId = "9941410184810"
                        },
                        new
                        {
                            BookId = 21,
                            Author = "Madonna",
                            BookName = "Emo",
                            CurrentHolder = "semiotics",
                            IsbnId = "1172396131405"
                        },
                        new
                        {
                            BookId = 22,
                            Author = "Led Zeppelin",
                            BookName = "Emo",
                            CurrentHolder = "portland",
                            IsbnId = "4087944335345"
                        },
                        new
                        {
                            BookId = 23,
                            Author = "Manteca",
                            BookName = "Classic Funk",
                            CurrentHolder = "pork",
                            IsbnId = "3887648635491"
                        },
                        new
                        {
                            BookId = 24,
                            Author = "DJ Jazzy Jeff and the Fresh Prince",
                            BookName = "Jazz",
                            CurrentHolder = "raw",
                            IsbnId = "2915862688289"
                        },
                        new
                        {
                            BookId = 25,
                            Author = "Luke & The Apostles",
                            BookName = "African Folk",
                            CurrentHolder = "way",
                            IsbnId = "2984041326206"
                        },
                        new
                        {
                            BookId = 26,
                            Author = "Moxy",
                            BookName = "R&B",
                            CurrentHolder = "of",
                            IsbnId = "9676182493416"
                        },
                        new
                        {
                            BookId = 27,
                            Author = "R.E.M.",
                            BookName = "Rock",
                            CurrentHolder = "gastropub",
                            IsbnId = "814946606203"
                        },
                        new
                        {
                            BookId = 28,
                            Author = "Matthew Good Band",
                            BookName = "Funk",
                            CurrentHolder = "richardson",
                            IsbnId = "3108339218007"
                        },
                        new
                        {
                            BookId = 29,
                            Author = "Letters to Elora",
                            BookName = "Pop",
                            CurrentHolder = "haven't",
                            IsbnId = "8705413680852"
                        },
                        new
                        {
                            BookId = 30,
                            Author = "Magneta Lane",
                            BookName = "Jazz",
                            CurrentHolder = "pour-over",
                            IsbnId = "7053080344131"
                        },
                        new
                        {
                            BookId = 31,
                            Author = "The Lovely Feathers",
                            BookName = "Folk",
                            CurrentHolder = "company",
                            IsbnId = "9948221598727"
                        },
                        new
                        {
                            BookId = 32,
                            Author = "Paul McCartney",
                            BookName = "Screamo",
                            CurrentHolder = "work",
                            IsbnId = "6708801349955"
                        },
                        new
                        {
                            BookId = 33,
                            Author = "Elton John",
                            BookName = "Rock",
                            CurrentHolder = "mustache",
                            IsbnId = "7920929988809"
                        },
                        new
                        {
                            BookId = 34,
                            Author = "Moxy",
                            BookName = "Rock",
                            CurrentHolder = "loko",
                            IsbnId = "6988596505014"
                        },
                        new
                        {
                            BookId = 35,
                            Author = "Major Maker",
                            BookName = "Easy Listening",
                            CurrentHolder = "cray",
                            IsbnId = "7242541446929"
                        },
                        new
                        {
                            BookId = 36,
                            Author = "Mahogany Rush",
                            BookName = "Kansas City Dance",
                            CurrentHolder = "company",
                            IsbnId = "9629478915421"
                        },
                        new
                        {
                            BookId = 37,
                            Author = "Cher",
                            BookName = "Kansas City Grunge",
                            CurrentHolder = "artisan",
                            IsbnId = "7672861510735"
                        },
                        new
                        {
                            BookId = 38,
                            Author = "Mean Red Spiders",
                            BookName = "Brazillian Grunge",
                            CurrentHolder = "keffiyeh",
                            IsbnId = "9559438405353"
                        },
                        new
                        {
                            BookId = 39,
                            Author = "Lillix",
                            BookName = "Acid Screamo",
                            CurrentHolder = "man",
                            IsbnId = "5677833448014"
                        },
                        new
                        {
                            BookId = 40,
                            Author = "Moxy",
                            BookName = "Funk",
                            CurrentHolder = "pickled",
                            IsbnId = "45284852406"
                        },
                        new
                        {
                            BookId = 41,
                            Author = "Olivia Newton-John",
                            BookName = "Screamo",
                            CurrentHolder = "apparel",
                            IsbnId = "6578884993949"
                        },
                        new
                        {
                            BookId = 42,
                            Author = "Low Level Flight",
                            BookName = "Glam Classical",
                            CurrentHolder = "bicycle",
                            IsbnId = "2093272270678"
                        },
                        new
                        {
                            BookId = 43,
                            Author = "Maow",
                            BookName = "Emo",
                            CurrentHolder = "etsy",
                            IsbnId = "6962296118476"
                        },
                        new
                        {
                            BookId = 44,
                            Author = "Prince",
                            BookName = "Brazillian Doo-Wop",
                            CurrentHolder = "shorts",
                            IsbnId = "4758487862888"
                        },
                        new
                        {
                            BookId = 45,
                            Author = "Martyr",
                            BookName = "Acid Jazz",
                            CurrentHolder = "way",
                            IsbnId = "3219813221702"
                        },
                        new
                        {
                            BookId = 46,
                            Author = "Luke & The Apostles",
                            BookName = "Doo-Wop",
                            CurrentHolder = "rights",
                            IsbnId = "1432375144880"
                        },
                        new
                        {
                            BookId = 47,
                            Author = "Lotus Child",
                            BookName = "Rock",
                            CurrentHolder = "narwhal",
                            IsbnId = "6730937169273"
                        },
                        new
                        {
                            BookId = 48,
                            Author = "Letters to Elora",
                            BookName = "Caribbean Jazz",
                            CurrentHolder = "echo",
                            IsbnId = "8235857439337"
                        },
                        new
                        {
                            BookId = 49,
                            Author = "Genesis",
                            BookName = "Jazz",
                            CurrentHolder = "Marfa",
                            IsbnId = "5756193444019"
                        },
                        new
                        {
                            BookId = 50,
                            Author = "Lace",
                            BookName = "Grunge",
                            CurrentHolder = "post-ironic",
                            IsbnId = "5555173687429"
                        },
                        new
                        {
                            BookId = 51,
                            Author = "B'z",
                            BookName = "Screamo",
                            CurrentHolder = "life",
                            IsbnId = "4737532145687"
                        },
                        new
                        {
                            BookId = 52,
                            Author = "Metric",
                            BookName = "Screamo",
                            CurrentHolder = "cosby",
                            IsbnId = "8481092019230"
                        },
                        new
                        {
                            BookId = 53,
                            Author = "Santana",
                            BookName = "House",
                            CurrentHolder = "occupy",
                            IsbnId = "2420131034413"
                        },
                        new
                        {
                            BookId = 54,
                            Author = "Mr. Pine",
                            BookName = "Kansas City Jazz",
                            CurrentHolder = "williamsburg",
                            IsbnId = "8654125541753"
                        },
                        new
                        {
                            BookId = 55,
                            Author = "Men Without Hats",
                            BookName = "Hard Screamo",
                            CurrentHolder = "pork",
                            IsbnId = "2043584697900"
                        },
                        new
                        {
                            BookId = 56,
                            Author = "The Most Serene Republic",
                            BookName = "Modern Jazz",
                            CurrentHolder = "semiotics",
                            IsbnId = "2732203692538"
                        },
                        new
                        {
                            BookId = 57,
                            Author = "Miriodor",
                            BookName = "Jazz",
                            CurrentHolder = "craft",
                            IsbnId = "7347847347775"
                        },
                        new
                        {
                            BookId = 58,
                            Author = "Metric",
                            BookName = "African Easy Listening",
                            CurrentHolder = "denim",
                            IsbnId = "1740114079667"
                        },
                        new
                        {
                            BookId = 59,
                            Author = "Rihanna",
                            BookName = "Doo-Wop",
                            CurrentHolder = "Ethnic",
                            IsbnId = "5438017302862"
                        },
                        new
                        {
                            BookId = 60,
                            Author = "Loverboy",
                            BookName = "Asian Screamo",
                            CurrentHolder = "park",
                            IsbnId = "9963307566923"
                        },
                        new
                        {
                            BookId = 61,
                            Author = "Moneyshot",
                            BookName = "Kansas City Folk",
                            CurrentHolder = "eye",
                            IsbnId = "8785521862462"
                        },
                        new
                        {
                            BookId = 62,
                            Author = "Eminem",
                            BookName = "Classic Rock",
                            CurrentHolder = "chips",
                            IsbnId = "9798436453472"
                        },
                        new
                        {
                            BookId = 63,
                            Author = "Phil Collins",
                            BookName = "Jazz",
                            CurrentHolder = "stumptown",
                            IsbnId = "215018806147"
                        },
                        new
                        {
                            BookId = 64,
                            Author = "Liferuiner",
                            BookName = "Emo",
                            CurrentHolder = "mlkshk",
                            IsbnId = "4507930611496"
                        },
                        new
                        {
                            BookId = 65,
                            Author = "Lioness",
                            BookName = "Blues",
                            CurrentHolder = "Marfa",
                            IsbnId = "8115255920270"
                        },
                        new
                        {
                            BookId = 66,
                            Author = "Lime",
                            BookName = "Jazzy R&B",
                            CurrentHolder = "narwhal",
                            IsbnId = "2570389459175"
                        },
                        new
                        {
                            BookId = 67,
                            Author = "The Luyas",
                            BookName = "African Grunge",
                            CurrentHolder = "Messenger",
                            IsbnId = "6497885089599"
                        },
                        new
                        {
                            BookId = 68,
                            Author = "Mes Aïeux",
                            BookName = "Grunge",
                            CurrentHolder = "gentrify",
                            IsbnId = "7720996298697"
                        },
                        new
                        {
                            BookId = 69,
                            Author = "Means",
                            BookName = "Modern Jazz",
                            CurrentHolder = "post-ironic",
                            IsbnId = "8246596906448"
                        },
                        new
                        {
                            BookId = 70,
                            Author = "Last Man Out",
                            BookName = "Hard Funk",
                            CurrentHolder = "sweater",
                            IsbnId = "2866657163420"
                        },
                        new
                        {
                            BookId = 71,
                            Author = "Love and Sas",
                            BookName = "Rock",
                            CurrentHolder = "photo",
                            IsbnId = "5140607205750"
                        },
                        new
                        {
                            BookId = 72,
                            Author = "Mecca Normal",
                            BookName = "Jazz",
                            CurrentHolder = "terry",
                            IsbnId = "3207988349352"
                        },
                        new
                        {
                            BookId = 73,
                            Author = "Library Voices",
                            BookName = "Blues",
                            CurrentHolder = "out",
                            IsbnId = "576347071014"
                        },
                        new
                        {
                            BookId = 74,
                            Author = "ABBA",
                            BookName = "Rock",
                            CurrentHolder = "of",
                            IsbnId = "2602954275255"
                        },
                        new
                        {
                            BookId = 75,
                            Author = "Mecca Normal",
                            BookName = "House",
                            CurrentHolder = "raw",
                            IsbnId = "624957890540"
                        },
                        new
                        {
                            BookId = 76,
                            Author = "Liferuiner",
                            BookName = "Classical",
                            CurrentHolder = "post-ironic",
                            IsbnId = "6341556560407"
                        },
                        new
                        {
                            BookId = 77,
                            Author = "Marilyn's Vitamins",
                            BookName = "Fresh Funk",
                            CurrentHolder = "haven't",
                            IsbnId = "4388080916548"
                        },
                        new
                        {
                            BookId = 78,
                            Author = "Lionel Richie",
                            BookName = "Rock",
                            CurrentHolder = "park",
                            IsbnId = "6391593472283"
                        },
                        new
                        {
                            BookId = 79,
                            Author = "Madonna",
                            BookName = "Brazillian Blues",
                            CurrentHolder = "cleanse",
                            IsbnId = "6958482166267"
                        },
                        new
                        {
                            BookId = 80,
                            Author = "Mudmen",
                            BookName = "Blues",
                            CurrentHolder = "life",
                            IsbnId = "8814098881005"
                        },
                        new
                        {
                            BookId = 81,
                            Author = "Mir",
                            BookName = "Blues",
                            CurrentHolder = "freegan",
                            IsbnId = "207678023822"
                        },
                        new
                        {
                            BookId = 82,
                            Author = "Bruce Springsteen",
                            BookName = "House",
                            CurrentHolder = "fap",
                            IsbnId = "9841521866545"
                        },
                        new
                        {
                            BookId = 83,
                            Author = "Martyr",
                            BookName = "Jazz",
                            CurrentHolder = "godard",
                            IsbnId = "4614578473667"
                        },
                        new
                        {
                            BookId = 84,
                            Author = "Luther Wright and the Wrongs",
                            BookName = "Asian Pop",
                            CurrentHolder = "messenger",
                            IsbnId = "412672693102"
                        },
                        new
                        {
                            BookId = 85,
                            Author = "Barry Manilow",
                            BookName = "Pop",
                            CurrentHolder = "8-bit",
                            IsbnId = "9577980898124"
                        },
                        new
                        {
                            BookId = 86,
                            Author = "Britney Spears",
                            BookName = "Glam Jazz",
                            CurrentHolder = "life",
                            IsbnId = "8729562279176"
                        },
                        new
                        {
                            BookId = 87,
                            Author = "Lava Hay",
                            BookName = "Brazillian Emo",
                            CurrentHolder = "fund",
                            IsbnId = "1551103015221"
                        },
                        new
                        {
                            BookId = 88,
                            Author = "Motion Ensemble",
                            BookName = "Folk",
                            CurrentHolder = "hella",
                            IsbnId = "6529237146735"
                        },
                        new
                        {
                            BookId = 89,
                            Author = "MacLean & MacLean",
                            BookName = "Fresh Classical",
                            CurrentHolder = "brooklyn",
                            IsbnId = "2207444506793"
                        },
                        new
                        {
                            BookId = 90,
                            Author = "Marilyn's Vitamins",
                            BookName = "Grunge",
                            CurrentHolder = "shorts",
                            IsbnId = "1772770454069"
                        },
                        new
                        {
                            BookId = 91,
                            Author = "Local Rabbits",
                            BookName = "Blues",
                            CurrentHolder = "kale",
                            IsbnId = "9544064267326"
                        },
                        new
                        {
                            BookId = 92,
                            Author = "The Latency",
                            BookName = "Classical",
                            CurrentHolder = "etsy",
                            IsbnId = "3195180130747"
                        },
                        new
                        {
                            BookId = 93,
                            Author = "Mudmen",
                            BookName = "Jazz",
                            CurrentHolder = "artisan",
                            IsbnId = "1383853802170"
                        },
                        new
                        {
                            BookId = 94,
                            Author = "Loverboy",
                            BookName = "Glam Blues",
                            CurrentHolder = "small",
                            IsbnId = "2976958580770"
                        },
                        new
                        {
                            BookId = 95,
                            Author = "Mir",
                            BookName = "African Rock",
                            CurrentHolder = "dreamcatcher",
                            IsbnId = "8522195689623"
                        },
                        new
                        {
                            BookId = 96,
                            Author = "The Doors",
                            BookName = "Screamo",
                            CurrentHolder = "retro",
                            IsbnId = "4042881240156"
                        },
                        new
                        {
                            BookId = 97,
                            Author = "The Manvils",
                            BookName = "Grunge",
                            CurrentHolder = "narwhal",
                            IsbnId = "9140686164209"
                        },
                        new
                        {
                            BookId = 98,
                            Author = "Moneen",
                            BookName = "Acid Easy Listening",
                            CurrentHolder = "part",
                            IsbnId = "9716798206659"
                        },
                        new
                        {
                            BookId = 99,
                            Author = "Means",
                            BookName = "Hard Rock",
                            CurrentHolder = "irony",
                            IsbnId = "3905664642297"
                        },
                        new
                        {
                            BookId = 100,
                            Author = "Major Maker",
                            BookName = "Doo-Wop",
                            CurrentHolder = "tofu",
                            IsbnId = "7911856462206"
                        },
                        new
                        {
                            BookId = 101,
                            Author = "Cher",
                            BookName = "Screamo",
                            CurrentHolder = "mumblecore",
                            IsbnId = "2196922754960"
                        },
                        new
                        {
                            BookId = 102,
                            Author = "Martha and the Muffins",
                            BookName = "Rock",
                            CurrentHolder = "Vinyl",
                            IsbnId = "6272373570256"
                        },
                        new
                        {
                            BookId = 103,
                            Author = "Queen",
                            BookName = "Jazz",
                            CurrentHolder = "art",
                            IsbnId = "7251693232567"
                        },
                        new
                        {
                            BookId = 104,
                            Author = "Live on Arrival",
                            BookName = "R&B",
                            CurrentHolder = "bag",
                            IsbnId = "151968980278"
                        },
                        new
                        {
                            BookId = 105,
                            Author = "Mahogany Rush",
                            BookName = "Kansas City Rock",
                            CurrentHolder = "ennui",
                            IsbnId = "7676999181358"
                        },
                        new
                        {
                            BookId = 106,
                            Author = "Lee Harvey Osmond",
                            BookName = "Grunge",
                            CurrentHolder = "thing",
                            IsbnId = "8791976496014"
                        },
                        new
                        {
                            BookId = 107,
                            Author = "Led Zeppelin",
                            BookName = "Classic Jazz",
                            CurrentHolder = "vegan",
                            IsbnId = "5167177647895"
                        },
                        new
                        {
                            BookId = 108,
                            Author = "Machete Avenue",
                            BookName = "Emo",
                            CurrentHolder = "master",
                            IsbnId = "7079609458837"
                        },
                        new
                        {
                            BookId = 109,
                            Author = "Prince",
                            BookName = "Jazz",
                            CurrentHolder = "semiotics",
                            IsbnId = "5291600350891"
                        },
                        new
                        {
                            BookId = 110,
                            Author = "Lost Dakotas",
                            BookName = "Doo-Wop",
                            CurrentHolder = "life",
                            IsbnId = "2964460837172"
                        },
                        new
                        {
                            BookId = 111,
                            Author = "Red Hot Chili Peppers",
                            BookName = "Classical",
                            CurrentHolder = "on",
                            IsbnId = "5606555475670"
                        },
                        new
                        {
                            BookId = 112,
                            Author = "Leahy",
                            BookName = "Caribbean Easy Listening",
                            CurrentHolder = "park",
                            IsbnId = "8218686575171"
                        },
                        new
                        {
                            BookId = 113,
                            Author = "Bryan Adams",
                            BookName = "African Easy Listening",
                            CurrentHolder = "you",
                            IsbnId = "2044064613079"
                        },
                        new
                        {
                            BookId = 114,
                            Author = "Neil Diamond",
                            BookName = "Blues",
                            CurrentHolder = "thing",
                            IsbnId = "3886351121536"
                        },
                        new
                        {
                            BookId = 115,
                            Author = "Bon Jovi",
                            BookName = "Rock",
                            CurrentHolder = "cred",
                            IsbnId = "7018062242780"
                        },
                        new
                        {
                            BookId = 116,
                            Author = "The Who",
                            BookName = "Grunge",
                            CurrentHolder = "wayfarers",
                            IsbnId = "6206432695596"
                        },
                        new
                        {
                            BookId = 117,
                            Author = "Elvis Presley",
                            BookName = "Electronic Folk",
                            CurrentHolder = "truffaut",
                            IsbnId = "2446290679483"
                        },
                        new
                        {
                            BookId = 118,
                            Author = "The Lovely Feathers",
                            BookName = "Asian House",
                            CurrentHolder = "Messenger",
                            IsbnId = "7064778812725"
                        },
                        new
                        {
                            BookId = 119,
                            Author = "Rihanna",
                            BookName = "Electronic Rock",
                            CurrentHolder = "richardson",
                            IsbnId = "2192382413052"
                        },
                        new
                        {
                            BookId = 120,
                            Author = "Memphis",
                            BookName = "Brazillian Classical",
                            CurrentHolder = "Four",
                            IsbnId = "6648126340773"
                        },
                        new
                        {
                            BookId = 121,
                            Author = "Lili Fatale",
                            BookName = "Jazz",
                            CurrentHolder = "vegan",
                            IsbnId = "8281719143633"
                        },
                        new
                        {
                            BookId = 122,
                            Author = "Mir",
                            BookName = "Jazz",
                            CurrentHolder = "farm-to-table",
                            IsbnId = "7231080642543"
                        },
                        new
                        {
                            BookId = 123,
                            Author = "Billy Joel",
                            BookName = "Rock",
                            CurrentHolder = "marfa",
                            IsbnId = "2775984491582"
                        },
                        new
                        {
                            BookId = 124,
                            Author = "Loverboy",
                            BookName = "Classic Children's",
                            CurrentHolder = "you",
                            IsbnId = "3736259152058"
                        },
                        new
                        {
                            BookId = 125,
                            Author = "The Lowest of the Low",
                            BookName = "Emo",
                            CurrentHolder = "ennui",
                            IsbnId = "585025595773"
                        },
                        new
                        {
                            BookId = 126,
                            Author = "LiveonRelease",
                            BookName = "Caribbean Emo",
                            CurrentHolder = "cleanse",
                            IsbnId = "9207859774682"
                        },
                        new
                        {
                            BookId = 127,
                            Author = "Leigh Ashford",
                            BookName = "Children's",
                            CurrentHolder = "8-bit",
                            IsbnId = "9086567246861"
                        },
                        new
                        {
                            BookId = 128,
                            Author = "Library Voices",
                            BookName = "Avant-Garde Jazz",
                            CurrentHolder = "vegan",
                            IsbnId = "4861821189924"
                        },
                        new
                        {
                            BookId = 129,
                            Author = "The Mahones",
                            BookName = "House",
                            CurrentHolder = "haven't",
                            IsbnId = "1343191285311"
                        },
                        new
                        {
                            BookId = 130,
                            Author = "Mythos",
                            BookName = "Rock",
                            CurrentHolder = "company",
                            IsbnId = "3844509350063"
                        },
                        new
                        {
                            BookId = 131,
                            Author = "The Matadors",
                            BookName = "Blues",
                            CurrentHolder = "eye",
                            IsbnId = "4463303095876"
                        },
                        new
                        {
                            BookId = 132,
                            Author = "The Memories Attack",
                            BookName = "Screamo",
                            CurrentHolder = "PBR",
                            IsbnId = "1933715409568"
                        },
                        new
                        {
                            BookId = 133,
                            Author = "The Mountains and the Trees",
                            BookName = "Easy Listening",
                            CurrentHolder = "dreamcatcher",
                            IsbnId = "9748361529665"
                        },
                        new
                        {
                            BookId = 134,
                            Author = "Metalwood",
                            BookName = "Rock",
                            CurrentHolder = "jean",
                            IsbnId = "6309058403740"
                        },
                        new
                        {
                            BookId = 135,
                            Author = "Leahy",
                            BookName = "Jazzy Blues",
                            CurrentHolder = "post-ironic",
                            IsbnId = "3879608825724"
                        },
                        new
                        {
                            BookId = 136,
                            Author = "Tina Turner",
                            BookName = "Classical",
                            CurrentHolder = "out",
                            IsbnId = "1197737153245"
                        },
                        new
                        {
                            BookId = 137,
                            Author = "Led Zeppelin",
                            BookName = "Dance",
                            CurrentHolder = "pickled",
                            IsbnId = "9852261333657"
                        },
                        new
                        {
                            BookId = 138,
                            Author = "L'Étranger",
                            BookName = "Jazz",
                            CurrentHolder = "park",
                            IsbnId = "1725042193068"
                        },
                        new
                        {
                            BookId = 139,
                            Author = "Chicago",
                            BookName = "Brazillian Blues",
                            CurrentHolder = "Umami",
                            IsbnId = "9998106211422"
                        },
                        new
                        {
                            BookId = 140,
                            Author = "Mr. Pine",
                            BookName = "Caribbean Jazz",
                            CurrentHolder = "probably",
                            IsbnId = "8048437101789"
                        },
                        new
                        {
                            BookId = 141,
                            Author = "Monster Voodoo Machine",
                            BookName = "Folk",
                            CurrentHolder = "high",
                            IsbnId = "824817330960"
                        },
                        new
                        {
                            BookId = 142,
                            Author = "Olivia Newton-John",
                            BookName = "Acid Emo",
                            CurrentHolder = "cosby",
                            IsbnId = "1733926256063"
                        },
                        new
                        {
                            BookId = 143,
                            Author = "Leslie Spit Treeo",
                            BookName = "African Funk",
                            CurrentHolder = "DIY",
                            IsbnId = "8500069495523"
                        },
                        new
                        {
                            BookId = 144,
                            Author = "Julio Iglesias",
                            BookName = "Dance",
                            CurrentHolder = "thundercats",
                            IsbnId = "6505416369300"
                        },
                        new
                        {
                            BookId = 145,
                            Author = "Lava Hay",
                            BookName = "Electronic Screamo",
                            CurrentHolder = "narwhal",
                            IsbnId = "3428647678079"
                        },
                        new
                        {
                            BookId = 146,
                            Author = "The Marble Index",
                            BookName = "Kansas City Folk",
                            CurrentHolder = "post-ironic",
                            IsbnId = "8587810391833"
                        },
                        new
                        {
                            BookId = 147,
                            Author = "Donna Summer",
                            BookName = "Brazillian Grunge",
                            CurrentHolder = "on",
                            IsbnId = "8413548217347"
                        },
                        new
                        {
                            BookId = 148,
                            Author = "Leigh Ashford",
                            BookName = "Rock",
                            CurrentHolder = "eye",
                            IsbnId = "4759935380313"
                        },
                        new
                        {
                            BookId = 149,
                            Author = "Moxy",
                            BookName = "Pop",
                            CurrentHolder = "farm-to-table",
                            IsbnId = "3221329037668"
                        },
                        new
                        {
                            BookId = 150,
                            Author = "The McDades",
                            BookName = "Kansas City Emo",
                            CurrentHolder = "of",
                            IsbnId = "9578195693706"
                        },
                        new
                        {
                            BookId = 151,
                            Author = "Garth Brooks",
                            BookName = "Dance",
                            CurrentHolder = "probably",
                            IsbnId = "8859023260352"
                        },
                        new
                        {
                            BookId = 152,
                            Author = "Masochistic Religion",
                            BookName = "Emo",
                            CurrentHolder = "master",
                            IsbnId = "9338340051164"
                        },
                        new
                        {
                            BookId = 153,
                            Author = "The Latency",
                            BookName = "African Jazz",
                            CurrentHolder = "richardson",
                            IsbnId = "4786848493286"
                        },
                        new
                        {
                            BookId = 154,
                            Author = "Barry Manilow",
                            BookName = "Rock",
                            CurrentHolder = "mlkshk",
                            IsbnId = "4519971001204"
                        },
                        new
                        {
                            BookId = 155,
                            Author = "Neil Diamond",
                            BookName = "Children's",
                            CurrentHolder = "truffaut",
                            IsbnId = "6892570018252"
                        },
                        new
                        {
                            BookId = 156,
                            Author = "Marilyn's Vitamins",
                            BookName = "Kansas City Classical",
                            CurrentHolder = "work",
                            IsbnId = "2228274812096"
                        },
                        new
                        {
                            BookId = 157,
                            Author = "L'Étranger",
                            BookName = "Children's",
                            CurrentHolder = "cray",
                            IsbnId = "758821778352"
                        },
                        new
                        {
                            BookId = 158,
                            Author = "Lioness",
                            BookName = "Jazzy Emo",
                            CurrentHolder = "american",
                            IsbnId = "777866780188"
                        },
                        new
                        {
                            BookId = 159,
                            Author = "Mir",
                            BookName = "Caribbean R&B",
                            CurrentHolder = "authentic",
                            IsbnId = "6829376084184"
                        },
                        new
                        {
                            BookId = 160,
                            Author = "Mes Aïeux",
                            BookName = "African House",
                            CurrentHolder = "park",
                            IsbnId = "5731572106355"
                        },
                        new
                        {
                            BookId = 161,
                            Author = "The Matadors",
                            BookName = "Classical",
                            CurrentHolder = "readymade",
                            IsbnId = "6967841948833"
                        },
                        new
                        {
                            BookId = 162,
                            Author = "Lee Harvey Osmond",
                            BookName = "Jazz",
                            CurrentHolder = "terry",
                            IsbnId = "7567789157651"
                        },
                        new
                        {
                            BookId = 163,
                            Author = "Miriodor",
                            BookName = "Jazz",
                            CurrentHolder = "dreamcatcher",
                            IsbnId = "2998850873205"
                        },
                        new
                        {
                            BookId = 164,
                            Author = "New Kids on the Block",
                            BookName = "Jazz",
                            CurrentHolder = "heard",
                            IsbnId = "8709523700508"
                        },
                        new
                        {
                            BookId = 165,
                            Author = "Limblifter",
                            BookName = "Emo",
                            CurrentHolder = "fanny",
                            IsbnId = "5763590440975"
                        },
                        new
                        {
                            BookId = 166,
                            Author = "Lime",
                            BookName = "Emo",
                            CurrentHolder = "shorts",
                            IsbnId = "935272765781"
                        },
                        new
                        {
                            BookId = 167,
                            Author = "Little Girls",
                            BookName = "Jazz",
                            CurrentHolder = "stumptown",
                            IsbnId = "5732757745186"
                        },
                        new
                        {
                            BookId = 168,
                            Author = "Matthew Good Band",
                            BookName = "Glam Jazz",
                            CurrentHolder = "etsy",
                            IsbnId = "2997438909019"
                        },
                        new
                        {
                            BookId = 169,
                            Author = "Lace",
                            BookName = "Emo",
                            CurrentHolder = "day",
                            IsbnId = "7269174995491"
                        },
                        new
                        {
                            BookId = 170,
                            Author = "Mythos",
                            BookName = "Easy Listening",
                            CurrentHolder = "stumptown",
                            IsbnId = "3082757789214"
                        },
                        new
                        {
                            BookId = 171,
                            Author = "The Matadors",
                            BookName = "Classic Emo",
                            CurrentHolder = "brunch",
                            IsbnId = "3616604061618"
                        },
                        new
                        {
                            BookId = 172,
                            Author = "Matt Mays & El Torpedo",
                            BookName = "Jazz",
                            CurrentHolder = "DIY",
                            IsbnId = "7983681186094"
                        },
                        new
                        {
                            BookId = 173,
                            Author = "Martyr",
                            BookName = "Children's",
                            CurrentHolder = "Gluten-free",
                            IsbnId = "4329105300982"
                        },
                        new
                        {
                            BookId = 174,
                            Author = "Merryweather",
                            BookName = "Electronic Screamo",
                            CurrentHolder = "echo",
                            IsbnId = "1406378010942"
                        },
                        new
                        {
                            BookId = 175,
                            Author = "Memphis",
                            BookName = "Asian Pop",
                            CurrentHolder = "kale",
                            IsbnId = "3085741709492"
                        },
                        new
                        {
                            BookId = 176,
                            Author = "Matthew Good Band",
                            BookName = "Jazzy Doo-Wop",
                            CurrentHolder = "tofu",
                            IsbnId = "3810225587249"
                        },
                        new
                        {
                            BookId = 177,
                            Author = "The Lovely Feathers",
                            BookName = "House",
                            CurrentHolder = "beer",
                            IsbnId = "5993443846699"
                        },
                        new
                        {
                            BookId = 178,
                            Author = "The Mark Inside",
                            BookName = "House",
                            CurrentHolder = "Iphone",
                            IsbnId = "3533000821961"
                        },
                        new
                        {
                            BookId = 179,
                            Author = "Magneta Lane",
                            BookName = "Brazillian Emo",
                            CurrentHolder = "heard",
                            IsbnId = "7570044173658"
                        },
                        new
                        {
                            BookId = 180,
                            Author = "Mariah Carey",
                            BookName = "Jazz",
                            CurrentHolder = "tofu",
                            IsbnId = "9259647903619"
                        },
                        new
                        {
                            BookId = 181,
                            Author = "Pink Floyd",
                            BookName = "Glam Emo",
                            CurrentHolder = "organic",
                            IsbnId = "8056744257014"
                        },
                        new
                        {
                            BookId = 182,
                            Author = "Bon Jovi",
                            BookName = "Avant-Garde R&B",
                            CurrentHolder = "before",
                            IsbnId = "1589064566227"
                        },
                        new
                        {
                            BookId = 183,
                            Author = "Martha and the Muffins",
                            BookName = "Jazz",
                            CurrentHolder = "on",
                            IsbnId = "8902924851934"
                        },
                        new
                        {
                            BookId = 184,
                            Author = "Paul McCartney",
                            BookName = "Hard Emo",
                            CurrentHolder = "pour-over",
                            IsbnId = "9027428291285"
                        },
                        new
                        {
                            BookId = 185,
                            Author = "Olivia Newton-John",
                            BookName = "Jazz",
                            CurrentHolder = "raw",
                            IsbnId = "2247918789390"
                        },
                        new
                        {
                            BookId = 186,
                            Author = "Chicago",
                            BookName = "Emo",
                            CurrentHolder = "trade",
                            IsbnId = "2387395744392"
                        },
                        new
                        {
                            BookId = 187,
                            Author = "Len",
                            BookName = "Emo",
                            CurrentHolder = "etsy",
                            IsbnId = "4409299615961"
                        },
                        new
                        {
                            BookId = 188,
                            Author = "Martyr",
                            BookName = "Free Grunge",
                            CurrentHolder = "future",
                            IsbnId = "2490823228140"
                        },
                        new
                        {
                            BookId = 189,
                            Author = "Eminem",
                            BookName = "Glam Easy Listening",
                            CurrentHolder = "terry",
                            IsbnId = "6678921085167"
                        },
                        new
                        {
                            BookId = 190,
                            Author = "Farm Fresh",
                            BookName = "Brazillian R&B",
                            CurrentHolder = "chips",
                            IsbnId = "8913766713307"
                        },
                        new
                        {
                            BookId = 191,
                            Author = "The Mark Inside",
                            BookName = "Grunge",
                            CurrentHolder = "etsy",
                            IsbnId = "7701348074572"
                        },
                        new
                        {
                            BookId = 192,
                            Author = "Bee Gees",
                            BookName = "Doo-Wop",
                            CurrentHolder = "semiotics",
                            IsbnId = "6336827253148"
                        },
                        new
                        {
                            BookId = 193,
                            Author = "The Rolling Stones",
                            BookName = "Acid Rock",
                            CurrentHolder = "organic",
                            IsbnId = "2158098808563"
                        },
                        new
                        {
                            BookId = 194,
                            Author = "The Manvils",
                            BookName = "Jazz",
                            CurrentHolder = "VHS",
                            IsbnId = "1528966804746"
                        },
                        new
                        {
                            BookId = 195,
                            Author = "The Mohawk Lodge",
                            BookName = "Kansas City Jazz",
                            CurrentHolder = "bag",
                            IsbnId = "8343027852635"
                        },
                        new
                        {
                            BookId = 196,
                            Author = "Garth Brooks",
                            BookName = "Hard Pop",
                            CurrentHolder = "part",
                            IsbnId = "519460872988"
                        },
                        new
                        {
                            BookId = 197,
                            Author = "Chicago",
                            BookName = "Rock",
                            CurrentHolder = "fund",
                            IsbnId = "5997508082537"
                        },
                        new
                        {
                            BookId = 198,
                            Author = "Barry Manilow",
                            BookName = "Electronic Rock",
                            CurrentHolder = "DIY",
                            IsbnId = "7052978494694"
                        },
                        new
                        {
                            BookId = 199,
                            Author = "Elvis Presley",
                            BookName = "Acid Blues",
                            CurrentHolder = "rights",
                            IsbnId = "8004258628005"
                        },
                        new
                        {
                            BookId = 200,
                            Author = "McKenna Mendelson Mainline",
                            BookName = "Funk",
                            CurrentHolder = "mixtape",
                            IsbnId = "9755807611977"
                        });
                });

            modelBuilder.Entity("Entities.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = 201,
                            BirthDate = new DateTime(1983, 5, 6, 6, 9, 38, 0, DateTimeKind.Unspecified),
                            EmailAddress = "charlessimmons@libra.ry",
                            FirstName = "Charles",
                            HomeAddress = "5356 Anthony Street ",
                            LastName = "Simmons",
                            Password = "they",
                            PhoneNumber = "(719) 795-9333",
                            RegistrationDate = new DateTime(2020, 4, 9, 19, 0, 34, 858, DateTimeKind.Local).AddTicks(4576),
                            Username = "charlessimmons"
                        },
                        new
                        {
                            MemberId = 202,
                            BirthDate = new DateTime(1976, 8, 10, 15, 33, 51, 0, DateTimeKind.Unspecified),
                            EmailAddress = "paigecox@libra.ry",
                            FirstName = "Paige",
                            HomeAddress = "9389 Berkeley Place ",
                            LastName = "Cox",
                            Password = "vice",
                            PhoneNumber = "(762) 212-5873",
                            RegistrationDate = new DateTime(2019, 9, 19, 19, 0, 34, 858, DateTimeKind.Local).AddTicks(6361),
                            Username = "paigecox"
                        },
                        new
                        {
                            MemberId = 203,
                            BirthDate = new DateTime(1911, 6, 29, 9, 54, 10, 0, DateTimeKind.Unspecified),
                            EmailAddress = "petronilaadams@libra.ry",
                            FirstName = "Petronila",
                            HomeAddress = "1500 Gerritsen Avenue ",
                            LastName = "Adams",
                            Password = "organic",
                            PhoneNumber = "(237) 483-4614",
                            RegistrationDate = new DateTime(2019, 1, 2, 19, 0, 34, 858, DateTimeKind.Local).AddTicks(7011),
                            Username = "petronilaadams"
                        },
                        new
                        {
                            MemberId = 204,
                            BirthDate = new DateTime(1941, 12, 16, 8, 30, 42, 0, DateTimeKind.Unspecified),
                            EmailAddress = "christopherhoward@libra.ry",
                            FirstName = "Christopher",
                            HomeAddress = "2660 Radde Place ",
                            LastName = "Howard",
                            Password = "eye",
                            PhoneNumber = "(548) 698-0818",
                            RegistrationDate = new DateTime(2020, 2, 16, 19, 0, 34, 858, DateTimeKind.Local).AddTicks(7692),
                            Username = "christopherhoward"
                        },
                        new
                        {
                            MemberId = 205,
                            BirthDate = new DateTime(1997, 11, 25, 13, 48, 30, 0, DateTimeKind.Unspecified),
                            EmailAddress = "lesliebailey@libra.ry",
                            FirstName = "Leslie",
                            HomeAddress = "2136 Brighton Avenue ",
                            LastName = "Bailey",
                            Password = "them",
                            PhoneNumber = "(361) 276-4227",
                            RegistrationDate = new DateTime(2018, 10, 22, 19, 0, 34, 858, DateTimeKind.Local).AddTicks(8230),
                            Username = "lesliebailey"
                        },
                        new
                        {
                            MemberId = 206,
                            BirthDate = new DateTime(1999, 1, 4, 8, 53, 48, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jesusperez@libra.ry",
                            FirstName = "Jesus",
                            HomeAddress = "9015 Mc Kenny Street ",
                            LastName = "Perez",
                            Password = "richardson",
                            PhoneNumber = "(532) 271-3352",
                            RegistrationDate = new DateTime(2020, 5, 19, 19, 0, 34, 858, DateTimeKind.Local).AddTicks(8687),
                            Username = "jesusperez"
                        },
                        new
                        {
                            MemberId = 207,
                            BirthDate = new DateTime(2015, 10, 5, 20, 34, 14, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jordanallen@libra.ry",
                            FirstName = "Jordan",
                            HomeAddress = "9658 Bay 43rd Street ",
                            LastName = "Allen",
                            Password = "post-ironic",
                            PhoneNumber = "(215) 203-6990",
                            RegistrationDate = new DateTime(2020, 10, 25, 19, 0, 34, 858, DateTimeKind.Local).AddTicks(9283),
                            Username = "jordanallen"
                        },
                        new
                        {
                            MemberId = 208,
                            BirthDate = new DateTime(1941, 1, 30, 8, 42, 51, 0, DateTimeKind.Unspecified),
                            EmailAddress = "leroybennett@libra.ry",
                            FirstName = "Leroy",
                            HomeAddress = "2879 Veterans Avenue ",
                            LastName = "Bennett",
                            Password = "fixie",
                            PhoneNumber = "(759) 468-9781",
                            RegistrationDate = new DateTime(2018, 8, 28, 19, 0, 34, 859, DateTimeKind.Local).AddTicks(43),
                            Username = "leroybennett"
                        },
                        new
                        {
                            MemberId = 209,
                            BirthDate = new DateTime(1986, 12, 18, 18, 30, 45, 0, DateTimeKind.Unspecified),
                            EmailAddress = "michaeljames@libra.ry",
                            FirstName = "Michael",
                            HomeAddress = "8047 Suydam Street ",
                            LastName = "James",
                            Password = "batch",
                            PhoneNumber = "(408) 247-2316",
                            RegistrationDate = new DateTime(2020, 11, 24, 19, 0, 34, 859, DateTimeKind.Local).AddTicks(581),
                            Username = "michaeljames"
                        },
                        new
                        {
                            MemberId = 210,
                            BirthDate = new DateTime(1958, 11, 8, 5, 56, 59, 0, DateTimeKind.Unspecified),
                            EmailAddress = "angiethomas@libra.ry",
                            FirstName = "Angie",
                            HomeAddress = "5080 Locust Street ",
                            LastName = "Thomas",
                            Password = "richardson",
                            PhoneNumber = "(459) 240-7306",
                            RegistrationDate = new DateTime(2020, 1, 20, 19, 0, 34, 859, DateTimeKind.Local).AddTicks(1165),
                            Username = "angiethomas"
                        },
                        new
                        {
                            MemberId = 211,
                            BirthDate = new DateTime(2010, 2, 18, 7, 13, 27, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rosshughes@libra.ry",
                            FirstName = "Ross",
                            HomeAddress = "5334 Argyle Road ",
                            LastName = "Hughes",
                            Password = "of",
                            PhoneNumber = "(543) 718-7302",
                            RegistrationDate = new DateTime(2019, 10, 15, 19, 0, 34, 859, DateTimeKind.Local).AddTicks(1688),
                            Username = "rosshughes"
                        },
                        new
                        {
                            MemberId = 212,
                            BirthDate = new DateTime(2012, 7, 2, 6, 25, 59, 0, DateTimeKind.Unspecified),
                            EmailAddress = "katherinerivera@libra.ry",
                            FirstName = "Katherine",
                            HomeAddress = "688 Brighton 4th Street ",
                            LastName = "Rivera",
                            Password = "VHS",
                            PhoneNumber = "(703) 519-9958",
                            RegistrationDate = new DateTime(2020, 11, 11, 19, 0, 34, 859, DateTimeKind.Local).AddTicks(2224),
                            Username = "katherinerivera"
                        },
                        new
                        {
                            MemberId = 213,
                            BirthDate = new DateTime(1928, 9, 23, 2, 40, 37, 0, DateTimeKind.Unspecified),
                            EmailAddress = "haileydiaz@libra.ry",
                            FirstName = "Hailey",
                            HomeAddress = "8523 College Place ",
                            LastName = "Diaz",
                            Password = "world",
                            PhoneNumber = "(266) 773-4338",
                            RegistrationDate = new DateTime(2019, 9, 11, 19, 0, 34, 859, DateTimeKind.Local).AddTicks(2759),
                            Username = "haileydiaz"
                        },
                        new
                        {
                            MemberId = 214,
                            BirthDate = new DateTime(1966, 4, 28, 10, 46, 35, 0, DateTimeKind.Unspecified),
                            EmailAddress = "haileyrodriguez@libra.ry",
                            FirstName = "Hailey",
                            HomeAddress = "7562 Division Place ",
                            LastName = "Rodriguez",
                            Password = "cleanse",
                            PhoneNumber = "(240) 495-6278",
                            RegistrationDate = new DateTime(2019, 9, 1, 19, 0, 34, 859, DateTimeKind.Local).AddTicks(3251),
                            Username = "haileyrodriguez"
                        },
                        new
                        {
                            MemberId = 215,
                            BirthDate = new DateTime(1985, 7, 12, 0, 24, 31, 0, DateTimeKind.Unspecified),
                            EmailAddress = "gabrielleward@libra.ry",
                            FirstName = "Gabrielle",
                            HomeAddress = "1037 Avenue T  ",
                            LastName = "Ward",
                            Password = "sweater",
                            PhoneNumber = "(509) 229-4408",
                            RegistrationDate = new DateTime(2020, 4, 13, 19, 0, 34, 859, DateTimeKind.Local).AddTicks(3723),
                            Username = "gabrielleward"
                        },
                        new
                        {
                            MemberId = 216,
                            BirthDate = new DateTime(1933, 5, 11, 7, 18, 32, 0, DateTimeKind.Unspecified),
                            EmailAddress = "sophiaadams@libra.ry",
                            FirstName = "Sophia",
                            HomeAddress = "919 Hamilton Avenue ",
                            LastName = "Adams",
                            Password = "beer",
                            PhoneNumber = "(549) 322-9031",
                            RegistrationDate = new DateTime(2019, 5, 27, 19, 0, 34, 859, DateTimeKind.Local).AddTicks(4234),
                            Username = "sophiaadams"
                        },
                        new
                        {
                            MemberId = 217,
                            BirthDate = new DateTime(1945, 12, 12, 7, 4, 49, 0, DateTimeKind.Unspecified),
                            EmailAddress = "allisontimms@libra.ry",
                            FirstName = "Allison",
                            HomeAddress = "9977 Engert Avenue ",
                            LastName = "Timms",
                            Password = "Swag",
                            PhoneNumber = "(514) 619-9813",
                            RegistrationDate = new DateTime(2020, 8, 29, 19, 0, 34, 859, DateTimeKind.Local).AddTicks(4715),
                            Username = "allisontimms"
                        },
                        new
                        {
                            MemberId = 218,
                            BirthDate = new DateTime(1943, 4, 12, 1, 49, 49, 0, DateTimeKind.Unspecified),
                            EmailAddress = "pilarwalker@libra.ry",
                            FirstName = "Pilar",
                            HomeAddress = "828 Ludlam Place ",
                            LastName = "Walker",
                            Password = "art",
                            PhoneNumber = "(665) 482-5806",
                            RegistrationDate = new DateTime(2019, 12, 29, 19, 0, 34, 859, DateTimeKind.Local).AddTicks(5153),
                            Username = "pilarwalker"
                        },
                        new
                        {
                            MemberId = 219,
                            BirthDate = new DateTime(1974, 6, 29, 1, 22, 33, 0, DateTimeKind.Unspecified),
                            EmailAddress = "victoriawhite@libra.ry",
                            FirstName = "Victoria",
                            HomeAddress = "776 Harbor View Terrace ",
                            LastName = "White",
                            Password = "narwhal",
                            PhoneNumber = "(419) 635-2293",
                            RegistrationDate = new DateTime(2020, 10, 26, 19, 0, 34, 859, DateTimeKind.Local).AddTicks(5616),
                            Username = "victoriawhite"
                        },
                        new
                        {
                            MemberId = 220,
                            BirthDate = new DateTime(1963, 2, 13, 20, 52, 48, 0, DateTimeKind.Unspecified),
                            EmailAddress = "nicolereed@libra.ry",
                            FirstName = "Nicole",
                            HomeAddress = "7196 Avenue U  ",
                            LastName = "Reed",
                            Password = "art",
                            PhoneNumber = "(233) 440-6497",
                            RegistrationDate = new DateTime(2019, 12, 22, 19, 0, 34, 859, DateTimeKind.Local).AddTicks(6108),
                            Username = "nicolereed"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
