// <auto-generated />
using System;
using DataAccess.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20210116172530_BooksMembersAndBookTransactions")]
    partial class BooksMembersAndBookTransactions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Entities.Book", b =>
                {
                    b.Property<string>("IsbnId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("IsbnId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            IsbnId = "0725545535804",
                            Author = "Mood Ruff",
                            BookName = "Brazillian Blues",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "2933514939399",
                            Author = "Mean Red Spiders",
                            BookName = "Free House",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "0037562980050",
                            Author = "Machete Avenue",
                            BookName = "Avant-Garde Screamo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1943694288128",
                            Author = "Luke & The Apostles",
                            BookName = "African Easy Listening",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6996307138746",
                            Author = "Motion Ensemble",
                            BookName = "Rock",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "8884430349658",
                            Author = "Mashmakhan",
                            BookName = "Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5317442508468",
                            Author = "Garth Brooks",
                            BookName = "Grunge",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "8084258352231",
                            Author = "Memphis",
                            BookName = "Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6761850617114",
                            Author = "Whitney Houston",
                            BookName = "Free Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8960014674488",
                            Author = "Marianas Trench",
                            BookName = "Asian R&B",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2305675796769",
                            Author = "Memphis",
                            BookName = "Doo-Wop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6194326266454",
                            Author = "Metallica",
                            BookName = "Rock",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "6555271006005",
                            Author = "Elton John",
                            BookName = "Avant-Garde Grunge",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3770115271157",
                            Author = "Lola Dutronic",
                            BookName = "R&B",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9051229620060",
                            Author = "Lace",
                            BookName = "Modern Doo-Wop",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "7679266031499",
                            Author = "My Darkest Days",
                            BookName = "Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9651571266256",
                            Author = "Mythos",
                            BookName = "Avant-Garde R&B",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "5232321184640",
                            Author = "Liferuiner",
                            BookName = "Caribbean Blues",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "7787158063594",
                            Author = "Mood Ruff",
                            BookName = "Free Doo-Wop",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "0438249633900",
                            Author = "Mariah Carey",
                            BookName = "Brazillian Screamo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6026411374106",
                            Author = "The Doors",
                            BookName = "Free Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0980441392897",
                            Author = "Neil Diamond",
                            BookName = "Electronic Rock",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "5093807365907",
                            Author = "Monster Voodoo Machine",
                            BookName = "Jazzy Jazz",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "7603298650652",
                            Author = "Miriodor",
                            BookName = "Rock",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "4637463849314",
                            Author = "Low Level Flight",
                            BookName = "Jazzy Pop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7114236617792",
                            Author = "The Look People",
                            BookName = "Kansas City Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4541685771949",
                            Author = "Gloria Estefan",
                            BookName = "Free Dance",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2628961366926",
                            Author = "Moneyshot",
                            BookName = "Asian Screamo",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "7362391641019",
                            Author = "The Midway State",
                            BookName = "Kansas City Blues",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "3852352423417",
                            Author = "Low Level Flight",
                            BookName = "Rock",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "5611949897489",
                            Author = "ABBA",
                            BookName = "Modern Jazz",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "8266499255126",
                            Author = "Memoryhouse",
                            BookName = "Modern R&B",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "2984457052102",
                            Author = "Love Kills",
                            BookName = "Jazz",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "8489918600488",
                            Author = "Lightning Dust",
                            BookName = "Caribbean Easy Listening",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8867623864284",
                            Author = "Lava Hay",
                            BookName = "Hard Grunge",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1453281006625",
                            Author = "Merlin",
                            BookName = "Modern House",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6006565769273",
                            Author = "The Mountains and the Trees",
                            BookName = "Blues",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "9714392918444",
                            Author = "Luke & The Apostles",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8279986163902",
                            Author = "Lioness",
                            BookName = "Caribbean Pop",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "5646893737097",
                            Author = "Loverboy",
                            BookName = "Modern Pop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0725835086599",
                            Author = "MCJ & Cool G",
                            BookName = "African Funk",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "4440220354406",
                            Author = "Mythos",
                            BookName = "Electronic Doo-Wop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6982699533520",
                            Author = "R.E.M.",
                            BookName = "Avant-Garde Pop",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "4157287229149",
                            Author = "Lava Hay",
                            BookName = "Jazzy Children's",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8424411395266",
                            Author = "Britney Spears",
                            BookName = "Folk",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "4841890773253",
                            Author = "Lee Harvey Osmond",
                            BookName = "Brazillian Dance",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8886693418103",
                            Author = "Cher",
                            BookName = "Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1030149894769",
                            Author = "McKenna Mendelson Mainline",
                            BookName = "Acid Screamo",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "9015543158888",
                            Author = "Santana",
                            BookName = "Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0753318183725",
                            Author = "The Mohawk Lodge",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2610184643991",
                            Author = "Metallica",
                            BookName = "Doo-Wop",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "5529906484559",
                            Author = "The MRQ",
                            BookName = "Kansas City Screamo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4513514984905",
                            Author = "Mes Aïeux",
                            BookName = "Screamo",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "2674407776739",
                            Author = "Left Spine Down",
                            BookName = "Modern Folk",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "5862418576436",
                            Author = "Mountain City Four",
                            BookName = "Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4972406334861",
                            Author = "Pink Floyd",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8333214619056",
                            Author = "The Mark Inside",
                            BookName = "Kansas City Funk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2769878675958",
                            Author = "L'Étranger",
                            BookName = "Blues",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0213054249761",
                            Author = "The Look People",
                            BookName = "Asian Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7703965973671",
                            Author = "Neil Diamond",
                            BookName = "Classic Children's",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "7815464639168",
                            Author = "Mannequin Depressives",
                            BookName = "Hard Doo-Wop",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "7626922870768",
                            Author = "Monster Voodoo Machine",
                            BookName = "Jazzy Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2825369684465",
                            Author = "Main Source",
                            BookName = "Hard Classical",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6923385877249",
                            Author = "B'z",
                            BookName = "Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3075069507216",
                            Author = "Rod Stewart",
                            BookName = "Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7795354743626",
                            Author = "LiveonRelease",
                            BookName = "Jazz",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "3490537366659",
                            Author = "AC/DC",
                            BookName = "Emo",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "4632277637293",
                            Author = "Mercey Brothers",
                            BookName = "Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5629952957514",
                            Author = "Mare",
                            BookName = "African Funk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0358203163384",
                            Author = "The McRackins",
                            BookName = "Funk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8111189228505",
                            Author = "George Michael",
                            BookName = "Folk",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "9999625714697",
                            Author = "Love Kills",
                            BookName = "Funk",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "8794796870773",
                            Author = "ABBA",
                            BookName = "Folk",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "7261119608143",
                            Author = "Len",
                            BookName = "Free Grunge",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "5959941715144",
                            Author = "Library Voices",
                            BookName = "Glam Easy Listening",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2947387039936",
                            Author = "Olivia Newton-John",
                            BookName = "Avant-Garde Funk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0377104431791",
                            Author = "My Darkest Days",
                            BookName = "Brazillian Classical",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7092865378179",
                            Author = "Matthew Good Band",
                            BookName = "Acid Children's",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "5712306033608",
                            Author = "Billy Joel",
                            BookName = "Grunge",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "5932138226887",
                            Author = "Pink Floyd",
                            BookName = "Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6168045964950",
                            Author = "Prince",
                            BookName = "Classic Grunge",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9148681382505",
                            Author = "Paul McCartney",
                            BookName = "Free Folk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9809983240545",
                            Author = "Rihanna",
                            BookName = "Easy Listening",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1415313243733",
                            Author = "U2",
                            BookName = "Classic Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3764917024597",
                            Author = "Ladyhawk",
                            BookName = "Classical",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0609412017662",
                            Author = "Tina Turner",
                            BookName = "Dance",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "4823872463213",
                            Author = "MonkeyJunk",
                            BookName = "Free Screamo",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "5874965338111",
                            Author = "Matthew Good Band",
                            BookName = "Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4415533114415",
                            Author = "Eminem",
                            BookName = "Blues",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8092898307633",
                            Author = "ABBA",
                            BookName = "Blues",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "0385111691039",
                            Author = "The Musical Box",
                            BookName = "Doo-Wop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3104088182785",
                            Author = "MonkeyJunk",
                            BookName = "Modern Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5393879108567",
                            Author = "Lime",
                            BookName = "Modern Rock",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "1609105846406",
                            Author = "Love Inc.",
                            BookName = "Modern Grunge",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5432972861328",
                            Author = "LiveonRelease",
                            BookName = "Free Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3461574668372",
                            Author = "Mudmen",
                            BookName = "Grunge",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1537888735921",
                            Author = "Genesis",
                            BookName = "Modern Dance",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "9510496246130",
                            Author = "Men Without Hats",
                            BookName = "Pop",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "4572119476680",
                            Author = "Mr. Pine",
                            BookName = "African Doo-Wop",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "2796374690308",
                            Author = "Mystery",
                            BookName = "Blues",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0308031438887",
                            Author = "The Mynah Birds",
                            BookName = "Electronic Jazz",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "8511886251373",
                            Author = "Loverboy",
                            BookName = "Dance",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "5968647421690",
                            Author = "The Carpenters",
                            BookName = "Classic Rock",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "0796899588837",
                            Author = "Maow",
                            BookName = "Kansas City Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2679472798756",
                            Author = "Last Man Out",
                            BookName = "Kansas City Easy Listening",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "5566767220221",
                            Author = "New Kids on the Block",
                            BookName = "Rock",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "2336587518276",
                            Author = "Mudmen",
                            BookName = "Doo-Wop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8269446514442",
                            Author = "Barbra Streisand",
                            BookName = "Classic Emo",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "2293574215782",
                            Author = "MCJ & Cool G",
                            BookName = "Modern Jazz",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "3914557839122",
                            Author = "The Latency",
                            BookName = "Kansas City Easy Listening",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3164384730015",
                            Author = "The McRackins",
                            BookName = "Grunge",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2161688037979",
                            Author = "Last Man Out",
                            BookName = "Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1921717825362",
                            Author = "Mobile",
                            BookName = "Acid Classical",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2992433070788",
                            Author = "Red Hot Chili Peppers",
                            BookName = "Caribbean Pop",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "4302202036220",
                            Author = "The Memories Attack",
                            BookName = "Pop",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "1309828823060",
                            Author = "Mercy, the Sexton",
                            BookName = "Avant-Garde Rock",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "4011494769364",
                            Author = "Rihanna",
                            BookName = "Caribbean Grunge",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "2581278082718",
                            Author = "Lillix",
                            BookName = "Jazz",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "7921970869664",
                            Author = "Martyr",
                            BookName = "Acid Jazz",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "2315657165931",
                            Author = "Lola Dutronic",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3164987622496",
                            Author = "The Carpenters",
                            BookName = "Blues",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4043900950795",
                            Author = "Moev",
                            BookName = "Children's",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "0870494602193",
                            Author = "The Manvils",
                            BookName = "Electronic Children's",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "4651164133086",
                            Author = "Mes Aïeux",
                            BookName = "R&B",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5221462963219",
                            Author = "Malajube",
                            BookName = "Brazillian Rock",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "2207257133912",
                            Author = "The McRackins",
                            BookName = "Rock",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "8563915447642",
                            Author = "The Memories Attack",
                            BookName = "Folk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2644216084095",
                            Author = "Julio Iglesias",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9292065190615",
                            Author = "Last Man Out",
                            BookName = "Hard Emo",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "0442245915804",
                            Author = "Mercy, the Sexton",
                            BookName = "Folk",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "7211926682196",
                            Author = "Moneen",
                            BookName = "Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4049478632980",
                            Author = "Lost & Profound",
                            BookName = "Rock",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "1688392775136",
                            Author = "B'z",
                            BookName = "Folk",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "6680246324330",
                            Author = "Mahogany Rush",
                            BookName = "Dance",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "2248835142323",
                            Author = "The Luyas",
                            BookName = "Acid Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3599482494009",
                            Author = "Mahogany Rush",
                            BookName = "African Doo-Wop",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "0336034148709",
                            Author = "Machete Avenue",
                            BookName = "Hard Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4470402926473",
                            Author = "Mashmakhan",
                            BookName = "Easy Listening",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "2435323063146",
                            Author = "ABBA",
                            BookName = "Asian Funk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8244445119747",
                            Author = "The McDades",
                            BookName = "Acid Pop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0757780752973",
                            Author = "Letters to Elora",
                            BookName = "Grunge",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7898774542091",
                            Author = "Linda Ronstadt",
                            BookName = "Dance",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0954191374262",
                            Author = "The Moffatts",
                            BookName = "Classical",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5160418899766",
                            Author = "Barbra Streisand",
                            BookName = "Funk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1427385929186",
                            Author = "Marilyn's Vitamins",
                            BookName = "Glam Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1426587791587",
                            Author = "The Mahones",
                            BookName = "Easy Listening",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2085183045573",
                            Author = "Stevie Wonder",
                            BookName = "Folk",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "9764887193145",
                            Author = "Lightning Dust",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0995231063984",
                            Author = "Tina Turner",
                            BookName = "Fresh Folk",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "2533653007753",
                            Author = "New Kids on the Block",
                            BookName = "African Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7876871770107",
                            Author = "The Lincolns",
                            BookName = "Folk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6246234888316",
                            Author = "McMaster & James",
                            BookName = "Dance",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6176824908208",
                            Author = "Lost & Profound",
                            BookName = "Fresh Funk",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "3371688533088",
                            Author = "Lotus Child",
                            BookName = "Asian Rock",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "2477855734624",
                            Author = "Van Halen",
                            BookName = "Classical",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "3180778881558",
                            Author = "Mandala",
                            BookName = "Caribbean Emo",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "2939785929442",
                            Author = "The Lovely Feathers",
                            BookName = "Acid Emo",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "1589206302418",
                            Author = "Moev",
                            BookName = "Classical",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "1565152061195",
                            Author = "Live on Arrival",
                            BookName = "African Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0351137436078",
                            Author = "Prince",
                            BookName = "Easy Listening",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "8469298492804",
                            Author = "Messenjah",
                            BookName = "Doo-Wop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8624894095567",
                            Author = "The Doors",
                            BookName = "Dance",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7911490260411",
                            Author = "Maharahj",
                            BookName = "Glam Easy Listening",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9468246728590",
                            Author = "Magneta Lane",
                            BookName = "Pop",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "8960141290394",
                            Author = "The Latency",
                            BookName = "Dance",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "8911728488825",
                            Author = "Live on Arrival",
                            BookName = "Classic R&B",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7193263767095",
                            Author = "Julio Iglesias",
                            BookName = "Pop",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "1275002480578",
                            Author = "Van Halen",
                            BookName = "Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0038422671592",
                            Author = "Ladyhawk",
                            BookName = "Acid Folk",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "0136354245554",
                            Author = "Bruce Springsteen",
                            BookName = "Fresh Dance",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "6017692127932",
                            Author = "My Darkest Days",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6372664893402",
                            Author = "Madrid",
                            BookName = "Classical",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5571681776214",
                            Author = "Barry Manilow",
                            BookName = "Brazillian Jazz",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "5585238410789",
                            Author = "Leslie Spit Treeo",
                            BookName = "Folk",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "0166758327880",
                            Author = "Mean Red Spiders",
                            BookName = "Acid Funk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3923183477774",
                            Author = "The Doors",
                            BookName = "Avant-Garde Screamo",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "4174739224134",
                            Author = "The Lovely Feathers",
                            BookName = "House",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "0558763236576",
                            Author = "Lost & Profound",
                            BookName = "Acid House",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "7761264532525",
                            Author = "Bruce Springsteen",
                            BookName = "Rock",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "9759159170568",
                            Author = "Guns N' Roses",
                            BookName = "Blues",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "2972855150918",
                            Author = "McMaster & James",
                            BookName = "Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2666020193468",
                            Author = "The McRackins",
                            BookName = "Rock",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "5612802562220",
                            Author = "Lili Fatale",
                            BookName = "Screamo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4159169168430",
                            Author = "Lace",
                            BookName = "Folk",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "1802653704300",
                            Author = "Metric",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2676140970456",
                            Author = "New Kids on the Block",
                            BookName = "Children's",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "9387229753422",
                            Author = "Mandala",
                            BookName = "African Doo-Wop",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "8068594505941",
                            Author = "Moneen",
                            BookName = "Hard Children's",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3244345322661",
                            Author = "Manic Drive",
                            BookName = "Jazzy Doo-Wop",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "9711957228094",
                            Author = "The Most Serene Republic",
                            BookName = "Fresh R&B",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1276514262745",
                            Author = "The Lemon Bucket Orkestra",
                            BookName = "Rock",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "0200615710287",
                            Author = "Johnny Hallyday",
                            BookName = "Screamo",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "6846178429488",
                            Author = "The Lowest of the Low",
                            BookName = "Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5522001698557",
                            Author = "Santana",
                            BookName = "Acid R&B",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0444924673548",
                            Author = "Olivia Newton-John",
                            BookName = "Glam Emo",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "8397622112115",
                            Author = "Genesis",
                            BookName = "Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2256230460303",
                            Author = "Loverboy",
                            BookName = "Hard Dance",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "7327518863593",
                            Author = "LiveonRelease",
                            BookName = "Acid Children's",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "2655501742196",
                            Author = "Mahogany Rush",
                            BookName = "Blues",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "3077326835680",
                            Author = "Mecca Normal",
                            BookName = "Grunge",
                            Count = 1
                        });
                });

            modelBuilder.Entity("Entities.BookTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsbnId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.HasIndex("IsbnId");

                    b.HasIndex("MemberId");

                    b.ToTable("BookTransactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 21,
                            EndDate = new DateTime(1997, 3, 18, 10, 1, 35, 0, DateTimeKind.Unspecified),
                            IsbnId = "0725545535804",
                            MemberId = 1,
                            StartDate = new DateTime(1975, 7, 10, 5, 27, 20, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 22,
                            EndDate = new DateTime(1937, 1, 24, 19, 41, 18, 0, DateTimeKind.Unspecified),
                            IsbnId = "2933514939399",
                            MemberId = 2,
                            StartDate = new DateTime(1957, 5, 8, 7, 25, 26, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 23,
                            EndDate = new DateTime(1995, 11, 22, 17, 31, 15, 0, DateTimeKind.Unspecified),
                            IsbnId = "0037562980050",
                            MemberId = 3,
                            StartDate = new DateTime(2011, 12, 3, 4, 52, 23, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 24,
                            EndDate = new DateTime(2009, 2, 3, 11, 49, 38, 0, DateTimeKind.Unspecified),
                            IsbnId = "1943694288128",
                            MemberId = 4,
                            StartDate = new DateTime(1915, 7, 16, 20, 32, 44, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 25,
                            EndDate = new DateTime(1945, 10, 12, 20, 7, 22, 0, DateTimeKind.Unspecified),
                            IsbnId = "6996307138746",
                            MemberId = 5,
                            StartDate = new DateTime(1959, 10, 5, 4, 55, 40, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 26,
                            EndDate = new DateTime(2000, 7, 5, 6, 49, 18, 0, DateTimeKind.Unspecified),
                            IsbnId = "8884430349658",
                            MemberId = 6,
                            StartDate = new DateTime(1962, 8, 26, 20, 33, 56, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 27,
                            EndDate = new DateTime(1938, 6, 22, 6, 24, 5, 0, DateTimeKind.Unspecified),
                            IsbnId = "5317442508468",
                            MemberId = 7,
                            StartDate = new DateTime(1983, 12, 19, 1, 36, 22, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 28,
                            EndDate = new DateTime(2005, 2, 6, 12, 40, 12, 0, DateTimeKind.Unspecified),
                            IsbnId = "8084258352231",
                            MemberId = 8,
                            StartDate = new DateTime(1978, 3, 16, 10, 34, 41, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 29,
                            EndDate = new DateTime(2014, 9, 25, 8, 16, 17, 0, DateTimeKind.Unspecified),
                            IsbnId = "6761850617114",
                            MemberId = 9,
                            StartDate = new DateTime(1918, 3, 25, 19, 59, 38, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 30,
                            EndDate = new DateTime(1998, 4, 16, 14, 53, 35, 0, DateTimeKind.Unspecified),
                            IsbnId = "8960014674488",
                            MemberId = 10,
                            StartDate = new DateTime(1988, 8, 15, 0, 26, 52, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 31,
                            EndDate = new DateTime(1914, 11, 19, 23, 26, 54, 0, DateTimeKind.Unspecified),
                            IsbnId = "2305675796769",
                            MemberId = 11,
                            StartDate = new DateTime(1951, 11, 25, 15, 26, 5, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 32,
                            EndDate = new DateTime(1978, 2, 15, 7, 31, 17, 0, DateTimeKind.Unspecified),
                            IsbnId = "6194326266454",
                            MemberId = 12,
                            StartDate = new DateTime(1919, 1, 28, 7, 46, 52, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 33,
                            EndDate = new DateTime(1982, 7, 18, 12, 22, 48, 0, DateTimeKind.Unspecified),
                            IsbnId = "6555271006005",
                            MemberId = 13,
                            StartDate = new DateTime(1965, 12, 1, 18, 40, 34, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 34,
                            EndDate = new DateTime(1914, 9, 27, 18, 24, 30, 0, DateTimeKind.Unspecified),
                            IsbnId = "3770115271157",
                            MemberId = 14,
                            StartDate = new DateTime(1907, 1, 7, 21, 15, 18, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 35,
                            EndDate = new DateTime(1987, 8, 25, 9, 45, 52, 0, DateTimeKind.Unspecified),
                            IsbnId = "9051229620060",
                            MemberId = 15,
                            StartDate = new DateTime(1948, 1, 19, 12, 27, 10, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 36,
                            EndDate = new DateTime(1921, 2, 4, 11, 36, 48, 0, DateTimeKind.Unspecified),
                            IsbnId = "7679266031499",
                            MemberId = 16,
                            StartDate = new DateTime(2020, 1, 6, 0, 56, 51, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 37,
                            EndDate = new DateTime(1970, 2, 20, 7, 5, 11, 0, DateTimeKind.Unspecified),
                            IsbnId = "9651571266256",
                            MemberId = 17,
                            StartDate = new DateTime(1940, 7, 9, 6, 20, 35, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 38,
                            EndDate = new DateTime(1992, 1, 27, 11, 24, 3, 0, DateTimeKind.Unspecified),
                            IsbnId = "5232321184640",
                            MemberId = 18,
                            StartDate = new DateTime(2009, 12, 6, 13, 21, 32, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 39,
                            EndDate = new DateTime(1949, 8, 4, 20, 59, 13, 0, DateTimeKind.Unspecified),
                            IsbnId = "7787158063594",
                            MemberId = 19,
                            StartDate = new DateTime(1947, 8, 11, 18, 11, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 40,
                            EndDate = new DateTime(1915, 5, 3, 8, 52, 0, 0, DateTimeKind.Unspecified),
                            IsbnId = "0438249633900",
                            MemberId = 20,
                            StartDate = new DateTime(1988, 11, 3, 20, 28, 48, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            BirthDate = new DateTime(2002, 3, 7, 2, 28, 23, 0, DateTimeKind.Unspecified),
                            EmailAddress = "kelseyreed@libra.ry",
                            FirstName = "Kelsey",
                            HomeAddress = "1355 97th Street ",
                            LastName = "Reed",
                            Password = "marfa",
                            PhoneNumber = "(590) 240-4700",
                            RegistrationDate = new DateTime(2019, 4, 12, 20, 25, 30, 127, DateTimeKind.Local).AddTicks(6348),
                            Username = "kelseyreed"
                        },
                        new
                        {
                            MemberId = 2,
                            BirthDate = new DateTime(2009, 3, 12, 12, 40, 55, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jessicayoung@libra.ry",
                            FirstName = "Jessica",
                            HomeAddress = "5795 Indiana Place ",
                            LastName = "Young",
                            Password = "butcher",
                            PhoneNumber = "(713) 620-6378",
                            RegistrationDate = new DateTime(2018, 7, 30, 20, 25, 30, 127, DateTimeKind.Local).AddTicks(8300),
                            Username = "jessicayoung"
                        },
                        new
                        {
                            MemberId = 3,
                            BirthDate = new DateTime(1923, 6, 2, 4, 17, 37, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jordancollins@libra.ry",
                            FirstName = "Jordan",
                            HomeAddress = "6517 51st Street ",
                            LastName = "Collins",
                            Password = "high",
                            PhoneNumber = "(434) 439-3061",
                            RegistrationDate = new DateTime(2018, 12, 26, 20, 25, 30, 127, DateTimeKind.Local).AddTicks(8873),
                            Username = "jordancollins"
                        },
                        new
                        {
                            MemberId = 4,
                            BirthDate = new DateTime(1964, 12, 8, 6, 27, 19, 0, DateTimeKind.Unspecified),
                            EmailAddress = "courtneyrussell@libra.ry",
                            FirstName = "Courtney",
                            HomeAddress = "3091 Hamilton Manor  ",
                            LastName = "Russell",
                            Password = "american",
                            PhoneNumber = "(757) 504-2503",
                            RegistrationDate = new DateTime(2019, 5, 4, 20, 25, 30, 127, DateTimeKind.Local).AddTicks(9426),
                            Username = "courtneyrussell"
                        },
                        new
                        {
                            MemberId = 5,
                            BirthDate = new DateTime(1937, 2, 9, 12, 56, 22, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jackcooper@libra.ry",
                            FirstName = "Jack",
                            HomeAddress = "2713 Prince Street ",
                            LastName = "Cooper",
                            Password = "fap",
                            PhoneNumber = "(312) 273-1038",
                            RegistrationDate = new DateTime(2019, 1, 31, 20, 25, 30, 127, DateTimeKind.Local).AddTicks(9889),
                            Username = "jackcooper"
                        },
                        new
                        {
                            MemberId = 6,
                            BirthDate = new DateTime(1910, 6, 20, 21, 3, 22, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rachelflores@libra.ry",
                            FirstName = "Rachel",
                            HomeAddress = "1547 Bokee Court ",
                            LastName = "Flores",
                            Password = "cred",
                            PhoneNumber = "(613) 683-6210",
                            RegistrationDate = new DateTime(2019, 12, 14, 20, 25, 30, 128, DateTimeKind.Local).AddTicks(382),
                            Username = "rachelflores"
                        },
                        new
                        {
                            MemberId = 7,
                            BirthDate = new DateTime(1923, 11, 20, 18, 26, 29, 0, DateTimeKind.Unspecified),
                            EmailAddress = "gabriellacox@libra.ry",
                            FirstName = "Gabriella",
                            HomeAddress = "1552 92nd Street ",
                            LastName = "Cox",
                            Password = "future",
                            PhoneNumber = "(311) 355-1905",
                            RegistrationDate = new DateTime(2019, 2, 24, 20, 25, 30, 128, DateTimeKind.Local).AddTicks(855),
                            Username = "gabriellacox"
                        },
                        new
                        {
                            MemberId = 8,
                            BirthDate = new DateTime(1929, 10, 15, 18, 33, 47, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ericmitchell@libra.ry",
                            FirstName = "Eric",
                            HomeAddress = "5087 Lott Place ",
                            LastName = "Mitchell",
                            Password = "street",
                            PhoneNumber = "(710) 678-9374",
                            RegistrationDate = new DateTime(2020, 5, 29, 20, 25, 30, 128, DateTimeKind.Local).AddTicks(1336),
                            Username = "ericmitchell"
                        },
                        new
                        {
                            MemberId = 9,
                            BirthDate = new DateTime(1947, 11, 27, 11, 29, 50, 0, DateTimeKind.Unspecified),
                            EmailAddress = "savannahbailey@libra.ry",
                            FirstName = "Savannah",
                            HomeAddress = "1576 Marshall Street ",
                            LastName = "Bailey",
                            Password = "brunch",
                            PhoneNumber = "(655) 506-1182",
                            RegistrationDate = new DateTime(2020, 12, 13, 20, 25, 30, 128, DateTimeKind.Local).AddTicks(1839),
                            Username = "savannahbailey"
                        },
                        new
                        {
                            MemberId = 10,
                            BirthDate = new DateTime(1940, 2, 27, 8, 20, 42, 0, DateTimeKind.Unspecified),
                            EmailAddress = "connorbrown@libra.ry",
                            FirstName = "Connor",
                            HomeAddress = "5508 Marconi Place ",
                            LastName = "Brown",
                            Password = "post-ironic",
                            PhoneNumber = "(490) 531-6192",
                            RegistrationDate = new DateTime(2019, 3, 2, 20, 25, 30, 128, DateTimeKind.Local).AddTicks(2318),
                            Username = "connorbrown"
                        },
                        new
                        {
                            MemberId = 11,
                            BirthDate = new DateTime(1956, 6, 19, 15, 33, 47, 0, DateTimeKind.Unspecified),
                            EmailAddress = "alexandrapearson@libra.ry",
                            FirstName = "Alexandra",
                            HomeAddress = "3662 Hazel Court ",
                            LastName = "Pearson",
                            Password = "mumblecore",
                            PhoneNumber = "(309) 311-0159",
                            RegistrationDate = new DateTime(2020, 11, 2, 20, 25, 30, 128, DateTimeKind.Local).AddTicks(2809),
                            Username = "alexandrapearson"
                        },
                        new
                        {
                            MemberId = 12,
                            BirthDate = new DateTime(1978, 12, 4, 17, 19, 3, 0, DateTimeKind.Unspecified),
                            EmailAddress = "spencermartinez@libra.ry",
                            FirstName = "Spencer",
                            HomeAddress = "2311 Bay 25th Street ",
                            LastName = "Martinez",
                            Password = "beer",
                            PhoneNumber = "(723) 419-6925",
                            RegistrationDate = new DateTime(2020, 3, 5, 20, 25, 30, 128, DateTimeKind.Local).AddTicks(3284),
                            Username = "spencermartinez"
                        },
                        new
                        {
                            MemberId = 13,
                            BirthDate = new DateTime(1929, 1, 1, 5, 14, 21, 0, DateTimeKind.Unspecified),
                            EmailAddress = "lilyverstraete@libra.ry",
                            FirstName = "Lily",
                            HomeAddress = "2438 Driggs Avenue ",
                            LastName = "Verstraete",
                            Password = "tofu",
                            PhoneNumber = "(737) 655-0765",
                            RegistrationDate = new DateTime(2019, 4, 6, 20, 25, 30, 128, DateTimeKind.Local).AddTicks(3775),
                            Username = "lilyverstraete"
                        },
                        new
                        {
                            MemberId = 14,
                            BirthDate = new DateTime(1923, 12, 21, 4, 1, 52, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rachelhughes@libra.ry",
                            FirstName = "Rachel",
                            HomeAddress = "903 Oakland Place ",
                            LastName = "Hughes",
                            Password = "biodiesel",
                            PhoneNumber = "(516) 625-9089",
                            RegistrationDate = new DateTime(2018, 5, 10, 20, 25, 30, 128, DateTimeKind.Local).AddTicks(4263),
                            Username = "rachelhughes"
                        },
                        new
                        {
                            MemberId = 15,
                            BirthDate = new DateTime(1929, 2, 19, 4, 0, 43, 0, DateTimeKind.Unspecified),
                            EmailAddress = "stephentorres@libra.ry",
                            FirstName = "Stephen",
                            HomeAddress = "2907 Parade Place ",
                            LastName = "Torres",
                            Password = "pour-over",
                            PhoneNumber = "(705) 522-0426",
                            RegistrationDate = new DateTime(2019, 2, 7, 20, 25, 30, 128, DateTimeKind.Local).AddTicks(4737),
                            Username = "stephentorres"
                        },
                        new
                        {
                            MemberId = 16,
                            BirthDate = new DateTime(1945, 6, 6, 9, 35, 50, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rachelmitchell@libra.ry",
                            FirstName = "Rachel",
                            HomeAddress = "3749 Brighton 2nd Street ",
                            LastName = "Mitchell",
                            Password = "cleanse",
                            PhoneNumber = "(392) 734-5089",
                            RegistrationDate = new DateTime(2019, 10, 5, 20, 25, 30, 128, DateTimeKind.Local).AddTicks(5225),
                            Username = "rachelmitchell"
                        },
                        new
                        {
                            MemberId = 17,
                            BirthDate = new DateTime(1955, 1, 14, 2, 6, 34, 0, DateTimeKind.Unspecified),
                            EmailAddress = "codyramirez@libra.ry",
                            FirstName = "Cody",
                            HomeAddress = "1191 Union Avenue ",
                            LastName = "Ramirez",
                            Password = "rights",
                            PhoneNumber = "(292) 523-5803",
                            RegistrationDate = new DateTime(2019, 7, 29, 20, 25, 30, 128, DateTimeKind.Local).AddTicks(5673),
                            Username = "codyramirez"
                        },
                        new
                        {
                            MemberId = 18,
                            BirthDate = new DateTime(1903, 8, 2, 5, 57, 28, 0, DateTimeKind.Unspecified),
                            EmailAddress = "daltonhill@libra.ry",
                            FirstName = "Dalton",
                            HomeAddress = "5813 School Lane ",
                            LastName = "Hill",
                            Password = "post-ironic",
                            PhoneNumber = "(342) 363-3395",
                            RegistrationDate = new DateTime(2019, 3, 17, 20, 25, 30, 128, DateTimeKind.Local).AddTicks(6173),
                            Username = "daltonhill"
                        },
                        new
                        {
                            MemberId = 19,
                            BirthDate = new DateTime(1956, 12, 5, 20, 16, 8, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jasongomes@libra.ry",
                            FirstName = "Jason",
                            HomeAddress = "312 Elton Street ",
                            LastName = "Gomes",
                            Password = "beer",
                            PhoneNumber = "(261) 786-4677",
                            RegistrationDate = new DateTime(2020, 4, 7, 20, 25, 30, 128, DateTimeKind.Local).AddTicks(6635),
                            Username = "jasongomes"
                        },
                        new
                        {
                            MemberId = 20,
                            BirthDate = new DateTime(1905, 10, 5, 12, 2, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "tristanmcvicar@libra.ry",
                            FirstName = "Tristan",
                            HomeAddress = "3524 Albee Square ",
                            LastName = "Mc Vicar",
                            Password = "occupy",
                            PhoneNumber = "(236) 671-6464",
                            RegistrationDate = new DateTime(2018, 5, 17, 20, 25, 30, 129, DateTimeKind.Local).AddTicks(6197),
                            Username = "tristanmcvicar"
                        });
                });

            modelBuilder.Entity("Entities.BookTransaction", b =>
                {
                    b.HasOne("Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("IsbnId");

                    b.HasOne("Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
