// <auto-generated />
using System;
using DataAccess.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20210116171639_BookTransactions")]
    partial class BookTransactions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Entities.Book", b =>
                {
                    b.Property<string>("IsbnId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("IsbnId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            IsbnId = "7566978182067",
                            Author = "The Manvils",
                            BookName = "Classical",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4016344283136",
                            Author = "Letters to Elora",
                            BookName = "Avant-Garde Children's",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4885244068443",
                            Author = "Manteca",
                            BookName = "Funk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9491966923493",
                            Author = "Left Spine Down",
                            BookName = "Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6889629773489",
                            Author = "Moneen",
                            BookName = "Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9038110524465",
                            Author = "AC/DC",
                            BookName = "Children's",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8682541963320",
                            Author = "The Who",
                            BookName = "Brazillian Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4327640555308",
                            Author = "Mercey Brothers",
                            BookName = "Avant-Garde Folk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1507139565229",
                            Author = "Luciano Pavarotti",
                            BookName = "Acid Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0432048934301",
                            Author = "Lola Dutronic",
                            BookName = "Free Folk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9730097015298",
                            Author = "Leahy",
                            BookName = "Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1363954059778",
                            Author = "LiveonRelease",
                            BookName = "Hard Classical",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8998854048595",
                            Author = "Rihanna",
                            BookName = "Grunge",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8304590763036",
                            Author = "Manteca",
                            BookName = "Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1717993753416",
                            Author = "Mashmakhan",
                            BookName = "Jazzy Classical",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2590367690606",
                            Author = "Phil Collins",
                            BookName = "Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3430089775499",
                            Author = "Little Caesar and the Consuls",
                            BookName = "Classic Classical",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9280308286998",
                            Author = "Mobile",
                            BookName = "Classic Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7646690586523",
                            Author = "Leslie Spit Treeo",
                            BookName = "Glam Dance",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9578877800599",
                            Author = "New Kids on the Block",
                            BookName = "Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0550876969911",
                            Author = "Love Kills",
                            BookName = "Modern Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8885867267983",
                            Author = "Mecca Normal",
                            BookName = "Dance",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1845936791605",
                            Author = "Major Maker",
                            BookName = "Acid Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8488491841895",
                            Author = "Gloria Estefan",
                            BookName = "Funk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3043560012229",
                            Author = "MSTRKRFT",
                            BookName = "Fresh Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7567427201009",
                            Author = "Linda Ronstadt",
                            BookName = "Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2405412078906",
                            Author = "Mecca Normal",
                            BookName = "Brazillian Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1485712115018",
                            Author = "Olivia Newton-John",
                            BookName = "Electronic Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3437783344881",
                            Author = "Metric",
                            BookName = "Jazzy Grunge",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1399167854697",
                            Author = "Red Hot Chili Peppers",
                            BookName = "Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2886711755235",
                            Author = "The Musical Box",
                            BookName = "Glam R&B",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9644410619472",
                            Author = "Johnny Hallyday",
                            BookName = "Acid Children's",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8260343128226",
                            Author = "The Lovely Feathers",
                            BookName = "House",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2127077230662",
                            Author = "Neil Diamond",
                            BookName = "Easy Listening",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8941449512064",
                            Author = "Julio Iglesias",
                            BookName = "Kansas City Dance",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9971768195754",
                            Author = "Moneen",
                            BookName = "Jazzy Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1034062645625",
                            Author = "Mandala",
                            BookName = "Easy Listening",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5270594625972",
                            Author = "Billy Joel",
                            BookName = "Hard Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4905041205592",
                            Author = "The Lemon Bucket Orkestra",
                            BookName = "Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9203538107210",
                            Author = "The McDades",
                            BookName = "R&B",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4211189583329",
                            Author = "McKenna Mendelson Mainline",
                            BookName = "Grunge",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8816164982850",
                            Author = "Rod Stewart",
                            BookName = "Classical",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1679102917993",
                            Author = "Miriodor",
                            BookName = "Funk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0839986619801",
                            Author = "The Most Serene Republic",
                            BookName = "Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2825195305508",
                            Author = "DJ Jazzy Jeff and the Fresh Prince",
                            BookName = "Hard Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6564697132668",
                            Author = "Madrid",
                            BookName = "Kansas City R&B",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7100801826508",
                            Author = "Donna Summer",
                            BookName = "Jazzy Screamo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9006292287016",
                            Author = "Main Source",
                            BookName = "Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5373069546000",
                            Author = "The Lincolns",
                            BookName = "Asian Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9897703681371",
                            Author = "Donna Summer",
                            BookName = "Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1762765469132",
                            Author = "Donna Summer",
                            BookName = "Acid Folk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5880067511871",
                            Author = "The Carpenters",
                            BookName = "Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4440915288299",
                            Author = "Lili Fatale",
                            BookName = "Folk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6116939089214",
                            Author = "The Mohawk Lodge",
                            BookName = "Acid Dance",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6976416123070",
                            Author = "Metric",
                            BookName = "Acid Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5943539087336",
                            Author = "Janet Jackson",
                            BookName = "Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9432835664783",
                            Author = "Dire Straits",
                            BookName = "Fresh Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3659180399802",
                            Author = "Lili Fatale",
                            BookName = "Pop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3710825084517",
                            Author = "The Mahones",
                            BookName = "Free Folk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6584620745733",
                            Author = "My Darkest Days",
                            BookName = "House",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3895136618811",
                            Author = "L'Étranger",
                            BookName = "Caribbean Screamo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4459268021555",
                            Author = "Lola Dutronic",
                            BookName = "Kansas City Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8152285383680",
                            Author = "Mystery",
                            BookName = "Doo-Wop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7370399883784",
                            Author = "Metric",
                            BookName = "Folk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4807765352319",
                            Author = "MacLean & MacLean",
                            BookName = "Jazzy Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7348104569079",
                            Author = "Led Zeppelin",
                            BookName = "Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0366049104804",
                            Author = "Dire Straits",
                            BookName = "Doo-Wop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4134214991185",
                            Author = "Prince",
                            BookName = "Pop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6625579424224",
                            Author = "LMDS",
                            BookName = "Modern Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9008643730914",
                            Author = "Rod Stewart",
                            BookName = "Classical",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8818723218235",
                            Author = "Lace",
                            BookName = "R&B",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5421913322780",
                            Author = "Red Hot Chili Peppers",
                            BookName = "Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1637705254659",
                            Author = "The Lemon Bucket Orkestra",
                            BookName = "Asian Doo-Wop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5705570652565",
                            Author = "Bryan Adams",
                            BookName = "Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2630126390523",
                            Author = "Neil Diamond",
                            BookName = "Hard House",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8997120160314",
                            Author = "The Lowest of the Low",
                            BookName = "African Children's",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4469192523243",
                            Author = "Mercy, the Sexton",
                            BookName = "Doo-Wop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8268368345056",
                            Author = "The Mark Inside",
                            BookName = "Modern Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2925734709639",
                            Author = "The Mynah Birds",
                            BookName = "Doo-Wop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3741291052814",
                            Author = "Billy Joel",
                            BookName = "Modern Dance",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7729043547754",
                            Author = "Love and Sas",
                            BookName = "Acid Folk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0661547965142",
                            Author = "Local Rabbits",
                            BookName = "House",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3375070742270",
                            Author = "Phil Collins",
                            BookName = "African Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0802517836762",
                            Author = "Celine Dion",
                            BookName = "Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6898820558819",
                            Author = "Johnny Hallyday",
                            BookName = "Classic Funk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4269072416616",
                            Author = "Chicago",
                            BookName = "Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2465933504425",
                            Author = "The Luyas",
                            BookName = "Fresh Easy Listening",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9405832212264",
                            Author = "Madrid",
                            BookName = "Caribbean Pop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2413089280845",
                            Author = "Main Source",
                            BookName = "Kansas City Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0260348597980",
                            Author = "Lola Dutronic",
                            BookName = "Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7801350704225",
                            Author = "Lionel Richie",
                            BookName = "Jazzy Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4637310419076",
                            Author = "Genesis",
                            BookName = "Hard Folk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8822187714707",
                            Author = "Gloria Estefan",
                            BookName = "Hard Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5582848633111",
                            Author = "Farm Fresh",
                            BookName = "Electronic Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2570839661651",
                            Author = "Last Man Out",
                            BookName = "Glam Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7014349735026",
                            Author = "Manteca",
                            BookName = "Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7926307772423",
                            Author = "Mudmen",
                            BookName = "Free Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1571131207462",
                            Author = "Stevie Wonder",
                            BookName = "Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3294649440734",
                            Author = "Little Girls",
                            BookName = "Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2739518909682",
                            Author = "The Mohawk Lodge",
                            BookName = "Avant-Garde Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3461096201116",
                            Author = "Low Level Flight",
                            BookName = "Modern Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0229025008576",
                            Author = "Live on Arrival",
                            BookName = "Electronic Grunge",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9643141036044",
                            Author = "The Lovely Feathers",
                            BookName = "Screamo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3626853988339",
                            Author = "Mountain City Four",
                            BookName = "Hard Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8341408636389",
                            Author = "The Marble Index",
                            BookName = "Easy Listening",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3603260319605",
                            Author = "Land of Talk",
                            BookName = "Folk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1504790430465",
                            Author = "My Darkest Days",
                            BookName = "Avant-Garde Folk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5997762808987",
                            Author = "Me Mom & Morgentaler",
                            BookName = "Folk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0749240871945",
                            Author = "Moev",
                            BookName = "Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5241714136009",
                            Author = "Motion Ensemble",
                            BookName = "Fresh Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8736774737346",
                            Author = "Mir",
                            BookName = "Modern Pop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8426895492979",
                            Author = "Mashmakhan",
                            BookName = "Jazzy Screamo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7995863863415",
                            Author = "Manic Drive",
                            BookName = "African Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7231952204957",
                            Author = "The Mynah Birds",
                            BookName = "Asian Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6118005371231",
                            Author = "Frank Sinatra",
                            BookName = "Screamo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0496026826921",
                            Author = "Dire Straits",
                            BookName = "Acid Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8346615452538",
                            Author = "Mare",
                            BookName = "Kansas City Folk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4612205720170",
                            Author = "ABBA",
                            BookName = "Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7733997498219",
                            Author = "ABBA",
                            BookName = "Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7801111108956",
                            Author = "Farm Fresh",
                            BookName = "Fresh Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2144609237906",
                            Author = "Phil Collins",
                            BookName = "Classic Folk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8222625065793",
                            Author = "Messenjah",
                            BookName = "Classic Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8983543883592",
                            Author = "Metalwood",
                            BookName = "Hard Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3627668999497",
                            Author = "The Beatles",
                            BookName = "Brazillian Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8469711199942",
                            Author = "Love Inc.",
                            BookName = "Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1443840972412",
                            Author = "Mannequin Depressives",
                            BookName = "Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3862153781325",
                            Author = "Metallica",
                            BookName = "Asian Easy Listening",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3317284794800",
                            Author = "The Mahones",
                            BookName = "Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0397179164165",
                            Author = "Luther Wright and the Wrongs",
                            BookName = "Modern Doo-Wop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2878204828748",
                            Author = "The McRackins",
                            BookName = "Avant-Garde House",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8333240561144",
                            Author = "Monster Voodoo Machine",
                            BookName = "Fresh House",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0160499489034",
                            Author = "Madrid",
                            BookName = "House",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2236157077574",
                            Author = "Lime",
                            BookName = "Children's",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7448643973209",
                            Author = "The McRackins",
                            BookName = "Asian Folk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7542623024950",
                            Author = "Chicago",
                            BookName = "African Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4762456712431",
                            Author = "Moneen",
                            BookName = "African Funk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8280825102352",
                            Author = "The Mohawk Lodge",
                            BookName = "African Pop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7010644927183",
                            Author = "The Carpenters",
                            BookName = "Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9723527373626",
                            Author = "The Mynah Birds",
                            BookName = "Classical",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0557998412466",
                            Author = "Mariah Carey",
                            BookName = "Glam Easy Listening",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0026710159404",
                            Author = "B'z",
                            BookName = "Free Pop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3730598868691",
                            Author = "Little Caesar and the Consuls",
                            BookName = "Modern Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5919019513571",
                            Author = "The Lowest of the Low",
                            BookName = "Pop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4433793318090",
                            Author = "Lili Fatale",
                            BookName = "Avant-Garde Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8785982033887",
                            Author = "Live on Arrival",
                            BookName = "Screamo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6636883384498",
                            Author = "Donna Summer",
                            BookName = "Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3903864728913",
                            Author = "Eagles",
                            BookName = "Caribbean Easy Listening",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8852653683004",
                            Author = "Leahy",
                            BookName = "Funk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6727261435134",
                            Author = "Michael Jackson",
                            BookName = "Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9337231007984",
                            Author = "Malajube",
                            BookName = "Easy Listening",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5930152455742",
                            Author = "The McRackins",
                            BookName = "Classical",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0576530225506",
                            Author = "Little Caesar and the Consuls",
                            BookName = "House",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1099561882495",
                            Author = "Moneyshot",
                            BookName = "Glam Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2755956505031",
                            Author = "Dire Straits",
                            BookName = "Glam Pop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7857337845028",
                            Author = "Mecca Normal",
                            BookName = "Electronic Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2500889308575",
                            Author = "The Memories Attack",
                            BookName = "Electronic Folk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8507899298236",
                            Author = "Local Rabbits",
                            BookName = "Caribbean Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3277900209800",
                            Author = "Monster Voodoo Machine",
                            BookName = "Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2419560961650",
                            Author = "Lighthouse",
                            BookName = "Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4159995837230",
                            Author = "Luke & The Apostles",
                            BookName = "Grunge",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7003534711532",
                            Author = "Mir",
                            BookName = "Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5449933808917",
                            Author = "McMaster & James",
                            BookName = "R&B",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2863021818074",
                            Author = "Liferuiner",
                            BookName = "Fresh Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5133474216449",
                            Author = "New Kids on the Block",
                            BookName = "Acid Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4170901748118",
                            Author = "Longing for Dawn",
                            BookName = "Folk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5838713421565",
                            Author = "Lost Dakotas",
                            BookName = "Modern Doo-Wop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3453176588657",
                            Author = "The Beatles",
                            BookName = "Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7809648063458",
                            Author = "Madonna",
                            BookName = "Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6951757353259",
                            Author = "Billy Joel",
                            BookName = "Screamo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8617976832052",
                            Author = "Merryweather",
                            BookName = "Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9477619897822",
                            Author = "Michael Jackson",
                            BookName = "Caribbean Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8598398698607",
                            Author = "Malajube",
                            BookName = "Electronic Screamo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2151106519797",
                            Author = "Lotus Child",
                            BookName = "African Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4438437259005",
                            Author = "Library Voices",
                            BookName = "Acid Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5036839122804",
                            Author = "Mythos",
                            BookName = "Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5676438542467",
                            Author = "Stevie Wonder",
                            BookName = "Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9566033725474",
                            Author = "Lighthouse",
                            BookName = "Grunge",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1812188738755",
                            Author = "The Lincolns",
                            BookName = "Funk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2104105138863",
                            Author = "Matt Mays & El Torpedo",
                            BookName = "Electronic Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9095255988696",
                            Author = "Luke & The Apostles",
                            BookName = "Asian Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4802404416751",
                            Author = "Mythos",
                            BookName = "Avant-Garde Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2271928271573",
                            Author = "Lee Harvey Osmond",
                            BookName = "Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3852441532920",
                            Author = "Malhavoc",
                            BookName = "Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8322356329434",
                            Author = "Frank Sinatra",
                            BookName = "Modern Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4210470546260",
                            Author = "Kenny Rogers",
                            BookName = "Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5019148508890",
                            Author = "Moneyshot",
                            BookName = "Easy Listening",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6323365779792",
                            Author = "Major Maker",
                            BookName = "Asian Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6742628745796",
                            Author = "Bryan Adams",
                            BookName = "Pop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6853734301434",
                            Author = "Martha and the Muffins",
                            BookName = "Hard Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2304171889627",
                            Author = "Rod Stewart",
                            BookName = "Screamo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3516985587448",
                            Author = "Moxy",
                            BookName = "Electronic Screamo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2265353065805",
                            Author = "Lightning Dust",
                            BookName = "Kansas City Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1853512138786",
                            Author = "Marianas Trench",
                            BookName = "Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2825969709648",
                            Author = "Madrid",
                            BookName = "Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0816881874187",
                            Author = "Martyr",
                            BookName = "Glam Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "1839204523740",
                            Author = "Britney Spears",
                            BookName = "Kansas City R&B",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8129995223870",
                            Author = "Liferuiner",
                            BookName = "Classical",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8047973470376",
                            Author = "Love and Sas",
                            BookName = "Screamo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7525329743224",
                            Author = "Marilyn's Vitamins",
                            BookName = "Classical",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0209716785574",
                            Author = "The Lincolns",
                            BookName = "Blues",
                            Count = 0
                        });
                });

            modelBuilder.Entity("Entities.BookTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BookIsbnId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsbnId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.HasIndex("BookIsbnId");

                    b.HasIndex("MemberId");

                    b.ToTable("BookTransactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 21,
                            EndDate = new DateTime(1953, 8, 11, 18, 58, 32, 0, DateTimeKind.Unspecified),
                            IsbnId = "7566978182067",
                            MemberId = 1,
                            StartDate = new DateTime(1995, 8, 7, 18, 18, 5, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 22,
                            EndDate = new DateTime(2005, 1, 15, 21, 34, 24, 0, DateTimeKind.Unspecified),
                            IsbnId = "4016344283136",
                            MemberId = 2,
                            StartDate = new DateTime(1954, 10, 2, 8, 39, 17, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 23,
                            EndDate = new DateTime(1938, 10, 10, 14, 34, 39, 0, DateTimeKind.Unspecified),
                            IsbnId = "4885244068443",
                            MemberId = 3,
                            StartDate = new DateTime(1979, 4, 24, 18, 46, 3, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 24,
                            EndDate = new DateTime(1928, 12, 17, 19, 29, 53, 0, DateTimeKind.Unspecified),
                            IsbnId = "9491966923493",
                            MemberId = 4,
                            StartDate = new DateTime(1976, 1, 10, 16, 41, 58, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 25,
                            EndDate = new DateTime(2010, 8, 7, 17, 11, 43, 0, DateTimeKind.Unspecified),
                            IsbnId = "6889629773489",
                            MemberId = 5,
                            StartDate = new DateTime(2015, 8, 14, 12, 30, 21, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 26,
                            EndDate = new DateTime(1902, 7, 11, 19, 1, 1, 0, DateTimeKind.Unspecified),
                            IsbnId = "9038110524465",
                            MemberId = 6,
                            StartDate = new DateTime(1910, 2, 18, 13, 54, 1, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 27,
                            EndDate = new DateTime(1909, 4, 1, 22, 8, 50, 0, DateTimeKind.Unspecified),
                            IsbnId = "8682541963320",
                            MemberId = 7,
                            StartDate = new DateTime(1967, 12, 11, 2, 50, 41, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 28,
                            EndDate = new DateTime(1980, 1, 10, 21, 52, 24, 0, DateTimeKind.Unspecified),
                            IsbnId = "4327640555308",
                            MemberId = 8,
                            StartDate = new DateTime(2008, 11, 24, 0, 57, 4, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 29,
                            EndDate = new DateTime(1990, 9, 18, 16, 13, 13, 0, DateTimeKind.Unspecified),
                            IsbnId = "1507139565229",
                            MemberId = 9,
                            StartDate = new DateTime(2015, 9, 27, 13, 24, 52, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 30,
                            EndDate = new DateTime(1983, 6, 6, 2, 40, 12, 0, DateTimeKind.Unspecified),
                            IsbnId = "0432048934301",
                            MemberId = 10,
                            StartDate = new DateTime(1929, 1, 15, 3, 41, 26, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 31,
                            EndDate = new DateTime(1903, 4, 26, 19, 50, 23, 0, DateTimeKind.Unspecified),
                            IsbnId = "9730097015298",
                            MemberId = 11,
                            StartDate = new DateTime(2006, 8, 9, 23, 32, 16, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 32,
                            EndDate = new DateTime(1928, 3, 11, 15, 15, 28, 0, DateTimeKind.Unspecified),
                            IsbnId = "1363954059778",
                            MemberId = 12,
                            StartDate = new DateTime(1992, 1, 27, 18, 2, 31, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 33,
                            EndDate = new DateTime(2017, 9, 24, 3, 44, 26, 0, DateTimeKind.Unspecified),
                            IsbnId = "8998854048595",
                            MemberId = 13,
                            StartDate = new DateTime(1968, 12, 19, 11, 21, 25, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 34,
                            EndDate = new DateTime(1902, 10, 31, 5, 3, 16, 0, DateTimeKind.Unspecified),
                            IsbnId = "8304590763036",
                            MemberId = 14,
                            StartDate = new DateTime(1936, 1, 29, 21, 3, 24, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 35,
                            EndDate = new DateTime(1927, 10, 6, 8, 0, 39, 0, DateTimeKind.Unspecified),
                            IsbnId = "1717993753416",
                            MemberId = 15,
                            StartDate = new DateTime(1989, 10, 12, 15, 36, 44, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 36,
                            EndDate = new DateTime(2020, 12, 12, 14, 46, 26, 0, DateTimeKind.Unspecified),
                            IsbnId = "2590367690606",
                            MemberId = 16,
                            StartDate = new DateTime(1934, 5, 28, 22, 40, 47, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 37,
                            EndDate = new DateTime(1978, 10, 30, 1, 39, 32, 0, DateTimeKind.Unspecified),
                            IsbnId = "3430089775499",
                            MemberId = 17,
                            StartDate = new DateTime(1914, 8, 18, 9, 48, 51, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 38,
                            EndDate = new DateTime(1969, 4, 20, 19, 14, 1, 0, DateTimeKind.Unspecified),
                            IsbnId = "9280308286998",
                            MemberId = 18,
                            StartDate = new DateTime(2014, 7, 21, 13, 31, 19, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 39,
                            EndDate = new DateTime(2001, 2, 28, 2, 28, 16, 0, DateTimeKind.Unspecified),
                            IsbnId = "7646690586523",
                            MemberId = 19,
                            StartDate = new DateTime(2000, 9, 8, 19, 15, 31, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 40,
                            EndDate = new DateTime(1903, 11, 4, 19, 25, 45, 0, DateTimeKind.Unspecified),
                            IsbnId = "9578877800599",
                            MemberId = 20,
                            StartDate = new DateTime(1966, 10, 17, 4, 39, 37, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            BirthDate = new DateTime(1931, 9, 27, 18, 36, 49, 0, DateTimeKind.Unspecified),
                            EmailAddress = "emilytaylor@libra.ry",
                            FirstName = "Emily",
                            HomeAddress = "1720 Bay 37th Street ",
                            LastName = "Taylor",
                            Password = "terry",
                            PhoneNumber = "(507) 228-9600",
                            RegistrationDate = new DateTime(2020, 2, 3, 20, 16, 38, 521, DateTimeKind.Local).AddTicks(1531),
                            Username = "emilytaylor"
                        },
                        new
                        {
                            MemberId = 2,
                            BirthDate = new DateTime(2002, 9, 13, 13, 38, 9, 0, DateTimeKind.Unspecified),
                            EmailAddress = "gabrielcooper@libra.ry",
                            FirstName = "Gabriel",
                            HomeAddress = "7635 29th Street ",
                            LastName = "Cooper",
                            Password = "life",
                            PhoneNumber = "(216) 508-1205",
                            RegistrationDate = new DateTime(2018, 7, 13, 20, 16, 38, 521, DateTimeKind.Local).AddTicks(3433),
                            Username = "gabrielcooper"
                        },
                        new
                        {
                            MemberId = 3,
                            BirthDate = new DateTime(2011, 12, 20, 23, 55, 56, 0, DateTimeKind.Unspecified),
                            EmailAddress = "carolineedwards@libra.ry",
                            FirstName = "Caroline",
                            HomeAddress = "1478 Jackson Place ",
                            LastName = "Edwards",
                            Password = "art",
                            PhoneNumber = "(757) 492-2172",
                            RegistrationDate = new DateTime(2019, 7, 20, 20, 16, 38, 521, DateTimeKind.Local).AddTicks(3982),
                            Username = "carolineedwards"
                        },
                        new
                        {
                            MemberId = 4,
                            BirthDate = new DateTime(1935, 10, 11, 8, 53, 35, 0, DateTimeKind.Unspecified),
                            EmailAddress = "alexislong@libra.ry",
                            FirstName = "Alexis",
                            HomeAddress = "2831 Brighton 3rd Street ",
                            LastName = "Long",
                            Password = "denim",
                            PhoneNumber = "(597) 363-2480",
                            RegistrationDate = new DateTime(2019, 1, 30, 20, 16, 38, 521, DateTimeKind.Local).AddTicks(4463),
                            Username = "alexislong"
                        },
                        new
                        {
                            MemberId = 5,
                            BirthDate = new DateTime(2011, 5, 30, 12, 34, 26, 0, DateTimeKind.Unspecified),
                            EmailAddress = "colehenderson@libra.ry",
                            FirstName = "Cole",
                            HomeAddress = "1104 Evergreen Avenue ",
                            LastName = "Henderson",
                            Password = "future",
                            PhoneNumber = "(492) 224-9392",
                            RegistrationDate = new DateTime(2019, 10, 4, 20, 16, 38, 521, DateTimeKind.Local).AddTicks(4933),
                            Username = "colehenderson"
                        },
                        new
                        {
                            MemberId = 6,
                            BirthDate = new DateTime(1967, 5, 20, 13, 42, 52, 0, DateTimeKind.Unspecified),
                            EmailAddress = "angrodriguez@libra.ry",
                            FirstName = "Ang",
                            HomeAddress = "3373 Rodney Street ",
                            LastName = "Rodriguez",
                            Password = "post-ironic",
                            PhoneNumber = "(710) 482-5140",
                            RegistrationDate = new DateTime(2019, 6, 19, 20, 16, 38, 521, DateTimeKind.Local).AddTicks(5439),
                            Username = "angrodriguez"
                        },
                        new
                        {
                            MemberId = 7,
                            BirthDate = new DateTime(1961, 7, 25, 13, 57, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "nicoledavis@libra.ry",
                            FirstName = "Nicole",
                            HomeAddress = "4240 Conklin Avenue ",
                            LastName = "Davis",
                            Password = "irony",
                            PhoneNumber = "(612) 797-7823",
                            RegistrationDate = new DateTime(2019, 12, 9, 20, 16, 38, 521, DateTimeKind.Local).AddTicks(5927),
                            Username = "nicoledavis"
                        },
                        new
                        {
                            MemberId = 8,
                            BirthDate = new DateTime(1979, 12, 28, 0, 57, 49, 0, DateTimeKind.Unspecified),
                            EmailAddress = "williamhoward@libra.ry",
                            FirstName = "William",
                            HomeAddress = "6941 Atkins Avenue ",
                            LastName = "Howard",
                            Password = "Iphone",
                            PhoneNumber = "(502) 478-3759",
                            RegistrationDate = new DateTime(2019, 8, 27, 20, 16, 38, 521, DateTimeKind.Local).AddTicks(6364),
                            Username = "williamhoward"
                        },
                        new
                        {
                            MemberId = 9,
                            BirthDate = new DateTime(2018, 10, 30, 22, 38, 26, 0, DateTimeKind.Unspecified),
                            EmailAddress = "sebastianbaker@libra.ry",
                            FirstName = "Sebastian",
                            HomeAddress = "6698 Gates Avenue ",
                            LastName = "Baker",
                            Password = "park",
                            PhoneNumber = "(580) 584-4844",
                            RegistrationDate = new DateTime(2018, 6, 16, 20, 16, 38, 521, DateTimeKind.Local).AddTicks(6824),
                            Username = "sebastianbaker"
                        },
                        new
                        {
                            MemberId = 10,
                            BirthDate = new DateTime(1965, 3, 26, 19, 42, 19, 0, DateTimeKind.Unspecified),
                            EmailAddress = "taylorgreen@libra.ry",
                            FirstName = "Taylor",
                            HomeAddress = "3032 Schenectady Avenue ",
                            LastName = "Green",
                            Password = "Swag",
                            PhoneNumber = "(513) 413-3013",
                            RegistrationDate = new DateTime(2020, 12, 8, 20, 16, 38, 521, DateTimeKind.Local).AddTicks(7293),
                            Username = "taylorgreen"
                        },
                        new
                        {
                            MemberId = 11,
                            BirthDate = new DateTime(1952, 10, 29, 13, 46, 36, 0, DateTimeKind.Unspecified),
                            EmailAddress = "kylierussell@libra.ry",
                            FirstName = "Kylie",
                            HomeAddress = "5523 Ingraham Street ",
                            LastName = "Russell",
                            Password = "richardson",
                            PhoneNumber = "(396) 259-8595",
                            RegistrationDate = new DateTime(2019, 12, 6, 20, 16, 38, 521, DateTimeKind.Local).AddTicks(7808),
                            Username = "kylierussell"
                        },
                        new
                        {
                            MemberId = 12,
                            BirthDate = new DateTime(1903, 1, 29, 1, 13, 27, 0, DateTimeKind.Unspecified),
                            EmailAddress = "gabrielfoster@libra.ry",
                            FirstName = "Gabriel",
                            HomeAddress = "2391 Porter Avenue ",
                            LastName = "Foster",
                            Password = "a",
                            PhoneNumber = "(645) 751-8769",
                            RegistrationDate = new DateTime(2018, 9, 23, 20, 16, 38, 521, DateTimeKind.Local).AddTicks(8248),
                            Username = "gabrielfoster"
                        },
                        new
                        {
                            MemberId = 13,
                            BirthDate = new DateTime(2000, 4, 15, 19, 37, 6, 0, DateTimeKind.Unspecified),
                            EmailAddress = "emmawhite@libra.ry",
                            FirstName = "Emma",
                            HomeAddress = "3225 Windsor Place ",
                            LastName = "White",
                            Password = "terry",
                            PhoneNumber = "(632) 675-2454",
                            RegistrationDate = new DateTime(2020, 10, 31, 20, 16, 38, 521, DateTimeKind.Local).AddTicks(8714),
                            Username = "emmawhite"
                        },
                        new
                        {
                            MemberId = 14,
                            BirthDate = new DateTime(1940, 8, 9, 13, 45, 27, 0, DateTimeKind.Unspecified),
                            EmailAddress = "johnwalker@libra.ry",
                            FirstName = "John",
                            HomeAddress = "5111 72nd Street ",
                            LastName = "Walker",
                            Password = "cred",
                            PhoneNumber = "(493) 669-5648",
                            RegistrationDate = new DateTime(2019, 3, 20, 20, 16, 38, 521, DateTimeKind.Local).AddTicks(9207),
                            Username = "johnwalker"
                        },
                        new
                        {
                            MemberId = 15,
                            BirthDate = new DateTime(1960, 12, 6, 22, 21, 54, 0, DateTimeKind.Unspecified),
                            EmailAddress = "justinmorris@libra.ry",
                            FirstName = "Justin",
                            HomeAddress = "1603 Tabor Court ",
                            LastName = "Morris",
                            Password = "odd",
                            PhoneNumber = "(707) 309-5576",
                            RegistrationDate = new DateTime(2020, 6, 15, 20, 16, 38, 521, DateTimeKind.Local).AddTicks(9700),
                            Username = "justinmorris"
                        },
                        new
                        {
                            MemberId = 16,
                            BirthDate = new DateTime(1973, 4, 17, 13, 57, 52, 0, DateTimeKind.Unspecified),
                            EmailAddress = "destinyrussell@libra.ry",
                            FirstName = "Destiny",
                            HomeAddress = "6924 4th Street ",
                            LastName = "Russell",
                            Password = "kale",
                            PhoneNumber = "(314) 261-5992",
                            RegistrationDate = new DateTime(2018, 8, 12, 20, 16, 38, 522, DateTimeKind.Local).AddTicks(151),
                            Username = "destinyrussell"
                        },
                        new
                        {
                            MemberId = 17,
                            BirthDate = new DateTime(1948, 1, 29, 5, 46, 29, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jordanwashington@libra.ry",
                            FirstName = "Jordan",
                            HomeAddress = "835 Vandervoort Place ",
                            LastName = "Washington",
                            Password = "semiotics",
                            PhoneNumber = "(262) 354-9642",
                            RegistrationDate = new DateTime(2020, 7, 4, 20, 16, 38, 522, DateTimeKind.Local).AddTicks(606),
                            Username = "jordanwashington"
                        },
                        new
                        {
                            MemberId = 18,
                            BirthDate = new DateTime(2017, 8, 12, 23, 0, 40, 0, DateTimeKind.Unspecified),
                            EmailAddress = "kimberlyperez@libra.ry",
                            FirstName = "Kimberly",
                            HomeAddress = "274 Varick Avenue ",
                            LastName = "Perez",
                            Password = "you",
                            PhoneNumber = "(395) 572-7846",
                            RegistrationDate = new DateTime(2018, 10, 17, 20, 16, 38, 522, DateTimeKind.Local).AddTicks(1063),
                            Username = "kimberlyperez"
                        },
                        new
                        {
                            MemberId = 19,
                            BirthDate = new DateTime(1960, 10, 27, 10, 36, 29, 0, DateTimeKind.Unspecified),
                            EmailAddress = "lilyyoung@libra.ry",
                            FirstName = "Lily",
                            HomeAddress = "6229 40th Street ",
                            LastName = "Young",
                            Password = "art",
                            PhoneNumber = "(426) 372-9202",
                            RegistrationDate = new DateTime(2019, 4, 9, 20, 16, 38, 522, DateTimeKind.Local).AddTicks(1533),
                            Username = "lilyyoung"
                        },
                        new
                        {
                            MemberId = 20,
                            BirthDate = new DateTime(1953, 5, 21, 15, 14, 17, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jasonwilliams@libra.ry",
                            FirstName = "Jason",
                            HomeAddress = "1088 Hull Street ",
                            LastName = "Williams",
                            Password = "high",
                            PhoneNumber = "(700) 332-6562",
                            RegistrationDate = new DateTime(2019, 3, 4, 20, 16, 38, 522, DateTimeKind.Local).AddTicks(2003),
                            Username = "jasonwilliams"
                        });
                });

            modelBuilder.Entity("Entities.BookTransaction", b =>
                {
                    b.HasOne("Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookIsbnId");

                    b.HasOne("Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
