// <auto-generated />
using DataAccess.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentHolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsbnId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "readymade",
                            BookName = "american",
                            CurrentHolder = "street",
                            IsbnId = "mlkshk"
                        },
                        new
                        {
                            Id = 2,
                            Author = "fixie",
                            BookName = "whatever",
                            CurrentHolder = "haven't",
                            IsbnId = "fixie"
                        },
                        new
                        {
                            Id = 3,
                            Author = "loko",
                            BookName = "Lo-fi",
                            CurrentHolder = "occupy",
                            IsbnId = "they"
                        },
                        new
                        {
                            Id = 4,
                            Author = "rights",
                            BookName = "raw",
                            CurrentHolder = "part",
                            IsbnId = "art"
                        },
                        new
                        {
                            Id = 5,
                            Author = "richardson",
                            BookName = "apparel",
                            CurrentHolder = "beer",
                            IsbnId = "narwhal"
                        },
                        new
                        {
                            Id = 6,
                            Author = "narwhal",
                            BookName = "Iphone",
                            CurrentHolder = "kogi",
                            IsbnId = "freegan"
                        },
                        new
                        {
                            Id = 7,
                            Author = "pickled",
                            BookName = "company",
                            CurrentHolder = "Polaroid",
                            IsbnId = "DIY"
                        },
                        new
                        {
                            Id = 8,
                            Author = "keffiyeh",
                            BookName = "Ethnic",
                            CurrentHolder = "shorts",
                            IsbnId = "trust"
                        },
                        new
                        {
                            Id = 9,
                            Author = "bicycle",
                            BookName = "vice",
                            CurrentHolder = "park",
                            IsbnId = "ethnic"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Post-ironic",
                            BookName = "post-ironic",
                            CurrentHolder = "pickled",
                            IsbnId = "Marfa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
