// <auto-generated />
using System;
using DataAccess.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Entities.Book", b =>
                {
                    b.Property<string>("IsbnId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("IsbnId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            IsbnId = "9873236987863",
                            Author = "Lionel Richie",
                            BookName = "Avant-Garde Jazz",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "1121836716909",
                            Author = "Lillix",
                            BookName = "Children's",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3781351488822",
                            Author = "Manic Drive",
                            BookName = "Acid Funk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4551209642316",
                            Author = "Matt Mays & El Torpedo",
                            BookName = "Classic Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4604291978709",
                            Author = "Lime",
                            BookName = "Free Easy Listening",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "1703070095021",
                            Author = "Men Without Hats",
                            BookName = "Doo-Wop",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "6277784144998",
                            Author = "The Marble Index",
                            BookName = "Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0614768255994",
                            Author = "Phil Collins",
                            BookName = "African Folk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4184060162107",
                            Author = "Mir",
                            BookName = "Emo",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "8263914230537",
                            Author = "MacLean & MacLean",
                            BookName = "Modern Doo-Wop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2678584242192",
                            Author = "LMDS",
                            BookName = "Blues",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "6023819596204",
                            Author = "LiveonRelease",
                            BookName = "R&B",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "3531364637983",
                            Author = "Tina Turner",
                            BookName = "Easy Listening",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "4101158816482",
                            Author = "Kiss",
                            BookName = "Jazzy Blues",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "9954431440808",
                            Author = "Metalwood",
                            BookName = "Electronic Doo-Wop",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "6820228601671",
                            Author = "Mystery Machine",
                            BookName = "Children's",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5497895113704",
                            Author = "Miriodor",
                            BookName = "Grunge",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "7912779711027",
                            Author = "Lillix",
                            BookName = "Easy Listening",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8566581885485",
                            Author = "Mariah Carey",
                            BookName = "Funk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8463416977173",
                            Author = "Loco Locass",
                            BookName = "Classic Pop",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "1265627077590",
                            Author = "Left Spine Down",
                            BookName = "Fresh Pop",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "1574401049287",
                            Author = "Celine Dion",
                            BookName = "Jazzy House",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0446236583357",
                            Author = "Mr. Pine",
                            BookName = "Rock",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "4040868159992",
                            Author = "Men Without Hats",
                            BookName = "Rock",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "7276659921195",
                            Author = "Martyr",
                            BookName = "Brazillian Emo",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "8273652623835",
                            Author = "Love Kills",
                            BookName = "Kansas City Jazz",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "4002069527508",
                            Author = "Merryweather",
                            BookName = "Asian Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7410339716668",
                            Author = "Motion Ensemble",
                            BookName = "Blues",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "0939525329739",
                            Author = "The MRQ",
                            BookName = "Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2102923801667",
                            Author = "Mean Red Spiders",
                            BookName = "Jazzy Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8244427618029",
                            Author = "Lost & Profound",
                            BookName = "Classical",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "9561077218201",
                            Author = "The Manvils",
                            BookName = "Asian Screamo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "0812125901533",
                            Author = "George Michael",
                            BookName = "Acid Jazz",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "7695192056088",
                            Author = "Love Kills",
                            BookName = "House",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "8879478055740",
                            Author = "Red Hot Chili Peppers",
                            BookName = "Jazzy Grunge",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6206954569508",
                            Author = "Lava Hay",
                            BookName = "Electronic Rock",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "5266857416368",
                            Author = "Metric",
                            BookName = "Avant-Garde House",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2287910302161",
                            Author = "Matthew Good Band",
                            BookName = "Classic R&B",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2503263656763",
                            Author = "LiveonRelease",
                            BookName = "Hard Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1311526627469",
                            Author = "Mes Aïeux",
                            BookName = "African Dance",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "2842495863515",
                            Author = "Eminem",
                            BookName = "Grunge",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "1297407510709",
                            Author = "Major Maker",
                            BookName = "Glam Dance",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "5855777535170",
                            Author = "Donna Summer",
                            BookName = "Easy Listening",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "1790625049533",
                            Author = "Mood Ruff",
                            BookName = "Rock",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "9156666747904",
                            Author = "Mes Aïeux",
                            BookName = "R&B",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "1967462884311",
                            Author = "Mystery",
                            BookName = "Blues",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "3980609506830",
                            Author = "Lioness",
                            BookName = "Doo-Wop",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "7643121782578",
                            Author = "The Manvils",
                            BookName = "Asian Blues",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1907264062838",
                            Author = "The McRackins",
                            BookName = "Blues",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9146216172052",
                            Author = "Matthew Good Band",
                            BookName = "Kansas City Dance",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4436576966597",
                            Author = "Mes Aïeux",
                            BookName = "Blues",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1707400073269",
                            Author = "Means",
                            BookName = "Glam Funk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4458251614303",
                            Author = "Mariah Carey",
                            BookName = "Children's",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9737873064009",
                            Author = "Cher",
                            BookName = "Asian Doo-Wop",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "1599518498832",
                            Author = "The Mahones",
                            BookName = "Blues",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "5561264111829",
                            Author = "Monster Voodoo Machine",
                            BookName = "House",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "7938028306804",
                            Author = "L'Étranger",
                            BookName = "Emo",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "7002911502081",
                            Author = "Lace",
                            BookName = "Classical",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4536977894373",
                            Author = "The Marble Index",
                            BookName = "Jazz",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "3593067528125",
                            Author = "Lace",
                            BookName = "Asian Blues",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "4963438740764",
                            Author = "Kate and Anna McGarrigle",
                            BookName = "Hard Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6129882601582",
                            Author = "Memoryhouse",
                            BookName = "Emo",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "6937661099509",
                            Author = "The McRackins",
                            BookName = "Fresh Rock",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "9343564533692",
                            Author = "Moxy",
                            BookName = "Electronic R&B",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "7281914785760",
                            Author = "The Lincolns",
                            BookName = "Grunge",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0379925197243",
                            Author = "Monster Voodoo Machine",
                            BookName = "Classical",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2474111867925",
                            Author = "George Michael",
                            BookName = "Jazzy Folk",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "3098590755149",
                            Author = "Liferuiner",
                            BookName = "Blues",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2484108933994",
                            Author = "Metallica",
                            BookName = "Jazzy Emo",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "1009915044552",
                            Author = "Mercy, the Sexton",
                            BookName = "African Children's",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "8815799358556",
                            Author = "The Marble Index",
                            BookName = "Children's",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "0472412984797",
                            Author = "Ladyhawk",
                            BookName = "Dance",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "2671934227518",
                            Author = "Memphis",
                            BookName = "Funk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "4517493431268",
                            Author = "The Manvils",
                            BookName = "Classic Folk",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "2883359286910",
                            Author = "Men Without Hats",
                            BookName = "Caribbean Grunge",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7230647740134",
                            Author = "The Midway State",
                            BookName = "Glam Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2981051687370",
                            Author = "Memphis",
                            BookName = "Dance",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5918039707076",
                            Author = "Mannequin Depressives",
                            BookName = "Rock",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "2146629585341",
                            Author = "Tina Turner",
                            BookName = "Electronic Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "2571625210138",
                            Author = "Gloria Estefan",
                            BookName = "Pop",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "1555481290257",
                            Author = "Machete Avenue",
                            BookName = "Glam R&B",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "3621365918184",
                            Author = "The Musical Box",
                            BookName = "Classical",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "2765503827083",
                            Author = "Billy Joel",
                            BookName = "Modern Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9055727330939",
                            Author = "Bryan Adams",
                            BookName = "Emo",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "4928775008322",
                            Author = "Moist",
                            BookName = "Brazillian Emo",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "3799455718012",
                            Author = "Love Kills",
                            BookName = "Rock",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "2365263777151",
                            Author = "Mare",
                            BookName = "Acid Children's",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "8336661010777",
                            Author = "Kenny Rogers",
                            BookName = "Caribbean Pop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3358121730508",
                            Author = "Barry Manilow",
                            BookName = "Hard Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0580642117164",
                            Author = "Lightning Dust",
                            BookName = "Acid Grunge",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5531344435956",
                            Author = "New Kids on the Block",
                            BookName = "Pop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5526364087539",
                            Author = "Lost Dakotas",
                            BookName = "Blues",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "5013370581040",
                            Author = "The Look People",
                            BookName = "Fresh Grunge",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6172624301890",
                            Author = "Merryweather",
                            BookName = "Dance",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3610516059958",
                            Author = "Aerosmith",
                            BookName = "Emo",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "3975031435186",
                            Author = "Land of Talk",
                            BookName = "African Doo-Wop",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "1622164584453",
                            Author = "Lost Dakotas",
                            BookName = "Blues",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "3774631174731",
                            Author = "B'z",
                            BookName = "Modern Easy Listening",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "1771148437025",
                            Author = "The Mohawk Lodge",
                            BookName = "Classic Jazz",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "6039179723913",
                            Author = "Bon Jovi",
                            BookName = "Kansas City Doo-Wop",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "6755779189638",
                            Author = "Leslie Spit Treeo",
                            BookName = "House",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8144436924935",
                            Author = "Farm Fresh",
                            BookName = "Blues",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "2421451021836",
                            Author = "U2",
                            BookName = "Free Children's",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "8159767191538",
                            Author = "Major Maker",
                            BookName = "Classical",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "7592844986748",
                            Author = "The Carpenters",
                            BookName = "Classic Classical",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1226592155054",
                            Author = "Mandala",
                            BookName = "Blues",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "6297894019004",
                            Author = "Billy Joel",
                            BookName = "Jazzy Folk",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "7203176356287",
                            Author = "Magneta Lane",
                            BookName = "Jazz",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "4116951950351",
                            Author = "Merlin",
                            BookName = "Blues",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1631298931951",
                            Author = "Luciano Pavarotti",
                            BookName = "Acid Doo-Wop",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "9842640597713",
                            Author = "Metric",
                            BookName = "Free Doo-Wop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9282426772980",
                            Author = "Moneen",
                            BookName = "Blues",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "2118720089993",
                            Author = "Rihanna",
                            BookName = "Caribbean Jazz",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "9227770857489",
                            Author = "LMDS",
                            BookName = "Hard Dance",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "9300004411121",
                            Author = "U2",
                            BookName = "Free Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8604500995833",
                            Author = "Left Spine Down",
                            BookName = "Modern Jazz",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "0626816947751",
                            Author = "Barbra Streisand",
                            BookName = "Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "5144361941822",
                            Author = "Lili Fatale",
                            BookName = "Classic Rock",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "1677227698623",
                            Author = "The Most Serene Republic",
                            BookName = "Electronic Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0744897241000",
                            Author = "The Moffatts",
                            BookName = "Easy Listening",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "5277099593344",
                            Author = "The Moffatts",
                            BookName = "Electronic Jazz",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "1399889030400",
                            Author = "MacLean & MacLean",
                            BookName = "R&B",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "7002897197893",
                            Author = "Machete Avenue",
                            BookName = "Grunge",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "9165884990083",
                            Author = "ABBA",
                            BookName = "Avant-Garde Blues",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "2740998781849",
                            Author = "Matt Mays & El Torpedo",
                            BookName = "Easy Listening",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "0551853444270",
                            Author = "Lost & Profound",
                            BookName = "Electronic Blues",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "2721470577010",
                            Author = "Len",
                            BookName = "Rock",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "3761738098881",
                            Author = "Tina Turner",
                            BookName = "Glam Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8169405544562",
                            Author = "New Kids on the Block",
                            BookName = "Jazz",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6170746024978",
                            Author = "ABBA",
                            BookName = "Hard Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2870911328934",
                            Author = "B'z",
                            BookName = "Grunge",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "6468848685891",
                            Author = "Local Rabbits",
                            BookName = "Caribbean Emo",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "1409329443303",
                            Author = "Genesis",
                            BookName = "Classic Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3369878034680",
                            Author = "Lace",
                            BookName = "Glam Rock",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "3078274193752",
                            Author = "The Who",
                            BookName = "Classical",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "0673472538575",
                            Author = "Luciano Pavarotti",
                            BookName = "Grunge",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8462333069601",
                            Author = "Ladyhawk",
                            BookName = "Classic Jazz",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "1868154808798",
                            Author = "Bon Jovi",
                            BookName = "Acid House",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "8725310517445",
                            Author = "Miriodor",
                            BookName = "Asian R&B",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0964621026521",
                            Author = "Mecca Normal",
                            BookName = "Pop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4763989872261",
                            Author = "My Darkest Days",
                            BookName = "R&B",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "2424505594117",
                            Author = "Mountain City Four",
                            BookName = "Brazillian Grunge",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "1482147233679",
                            Author = "Mir",
                            BookName = "Caribbean Rock",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "8989250971809",
                            Author = "Fleetwood Mac",
                            BookName = "Jazz",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "8000419692704",
                            Author = "The Lincolns",
                            BookName = "Funk",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "3511355836228",
                            Author = "Library Voices",
                            BookName = "Acid Folk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0670072170800",
                            Author = "Chicago",
                            BookName = "Jazz",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "3048027896803",
                            Author = "Julio Iglesias",
                            BookName = "Funk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4135048064021",
                            Author = "Phil Collins",
                            BookName = "Free Folk",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "2268433237378",
                            Author = "Lotus Child",
                            BookName = "Emo",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "0610652660688",
                            Author = "Madonna",
                            BookName = "Classic Doo-Wop",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "3740230815885",
                            Author = "The Mark Inside",
                            BookName = "Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9359831649360",
                            Author = "Merlin",
                            BookName = "Avant-Garde Rock",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "8288679369278",
                            Author = "Lotus Child",
                            BookName = "African Doo-Wop",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "8024508303821",
                            Author = "Mare",
                            BookName = "Grunge",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2618328332491",
                            Author = "Mythos",
                            BookName = "Fresh Dance",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "8403967900293",
                            Author = "Metric",
                            BookName = "Glam Rock",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "0517994205005",
                            Author = "Lightning Dust",
                            BookName = "Electronic Grunge",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "2681206582942",
                            Author = "Max Webster",
                            BookName = "Hard Pop",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "4303429715730",
                            Author = "The McRackins",
                            BookName = "Jazz",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "5767549751296",
                            Author = "Bryan Adams",
                            BookName = "Doo-Wop",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "9798584093376",
                            Author = "Bon Jovi",
                            BookName = "Classical",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "6296198984977",
                            Author = "The Mountains and the Trees",
                            BookName = "Dance",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "5208634098625",
                            Author = "Left Spine Down",
                            BookName = "Kansas City Children's",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "6022805776271",
                            Author = "Ladyhawk",
                            BookName = "Blues",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "0636230085074",
                            Author = "ABBA",
                            BookName = "Caribbean Dance",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "5135535502929",
                            Author = "The Matadors",
                            BookName = "Glam Funk",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "6011270228565",
                            Author = "Michael Jackson",
                            BookName = "Classic House",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "3411934836990",
                            Author = "The Look People",
                            BookName = "Brazillian Emo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5888960045799",
                            Author = "Motion Ensemble",
                            BookName = "Classical",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "7404596099484",
                            Author = "Rihanna",
                            BookName = "Doo-Wop",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "6021080312206",
                            Author = "Lime",
                            BookName = "Modern Grunge",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3681479597629",
                            Author = "Loco Locass",
                            BookName = "Pop",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7975024845354",
                            Author = "R.E.M.",
                            BookName = "Asian Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "3243335541992",
                            Author = "Luke & The Apostles",
                            BookName = "Jazzy Jazz",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "0115012172481",
                            Author = "Manic Drive",
                            BookName = "Rock",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7180169969973",
                            Author = "Leslie Spit Treeo",
                            BookName = "African Folk",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5276064399338",
                            Author = "LMDS",
                            BookName = "Classic Rock",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "8427893470632",
                            Author = "Britney Spears",
                            BookName = "Jazzy R&B",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "6492071118873",
                            Author = "Bee Gees",
                            BookName = "Emo",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "7144209446723",
                            Author = "The Luyas",
                            BookName = "Avant-Garde Emo",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "6935870853460",
                            Author = "Moist",
                            BookName = "Acid Emo",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "6889118208112",
                            Author = "Mr. Pine",
                            BookName = "Hard Doo-Wop",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "3163400480438",
                            Author = "Linda Ronstadt",
                            BookName = "Asian Grunge",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "2822521537543",
                            Author = "Lighthouse",
                            BookName = "Glam Funk",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "6393108686301",
                            Author = "Love Kills",
                            BookName = "Funk",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4371435209784",
                            Author = "Whitney Houston",
                            BookName = "Pop",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "0383068247278",
                            Author = "Elvis Presley",
                            BookName = "Modern Emo",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "2607797904112",
                            Author = "Phil Collins",
                            BookName = "Folk",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "7722374034513",
                            Author = "The Lowest of the Low",
                            BookName = "Hard Dance",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "9531922811534",
                            Author = "Celine Dion",
                            BookName = "Screamo",
                            Count = 0
                        },
                        new
                        {
                            IsbnId = "5206777037849",
                            Author = "Julio Iglesias",
                            BookName = "Screamo",
                            Count = 4
                        },
                        new
                        {
                            IsbnId = "6449376399108",
                            Author = "Queen",
                            BookName = "Electronic Jazz",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "1684328974966",
                            Author = "Luther Wright and the Wrongs",
                            BookName = "Rock",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "2459509448477",
                            Author = "Guns N' Roses",
                            BookName = "Screamo",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "2227823952138",
                            Author = "Barry Manilow",
                            BookName = "Hard Blues",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "3390734782392",
                            Author = "Me Mom & Morgentaler",
                            BookName = "African Rock",
                            Count = 2
                        },
                        new
                        {
                            IsbnId = "3535931308307",
                            Author = "Mecca Normal",
                            BookName = "Free Jazz",
                            Count = 1
                        },
                        new
                        {
                            IsbnId = "0228883368791",
                            Author = "Kiss",
                            BookName = "Acid Dance",
                            Count = 3
                        },
                        new
                        {
                            IsbnId = "4626617780884",
                            Author = "The Mark Inside",
                            BookName = "Modern Emo",
                            Count = 3
                        });
                });

            modelBuilder.Entity("Entities.BookTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("IsbnId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionId");

                    b.HasIndex("IsbnId");

                    b.HasIndex("MemberId");

                    b.ToTable("BookTransactions");
                });

            modelBuilder.Entity("Entities.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            BirthDate = new DateTime(1945, 10, 9, 9, 48, 10, 0, DateTimeKind.Unspecified),
                            EmailAddress = "sydneyıginla@libra.ry",
                            FirstName = "Sydney",
                            HomeAddress = "5282 24th Street ",
                            LastName = "Iginla",
                            PhoneNumber = "(446) 428-6883",
                            RegistrationDate = new DateTime(2020, 6, 25, 0, 51, 59, 326, DateTimeKind.Local).AddTicks(4163)
                        },
                        new
                        {
                            MemberId = 2,
                            BirthDate = new DateTime(1924, 9, 6, 1, 9, 24, 0, DateTimeKind.Unspecified),
                            EmailAddress = "silviarichardson@libra.ry",
                            FirstName = "Silvia",
                            HomeAddress = "5173 Church Lane ",
                            LastName = "Richardson",
                            PhoneNumber = "(790) 488-7472",
                            RegistrationDate = new DateTime(2019, 2, 23, 0, 51, 59, 326, DateTimeKind.Local).AddTicks(6794)
                        },
                        new
                        {
                            MemberId = 3,
                            BirthDate = new DateTime(2019, 9, 2, 12, 59, 49, 0, DateTimeKind.Unspecified),
                            EmailAddress = "nataliefoster@libra.ry",
                            FirstName = "Natalie",
                            HomeAddress = "6274 Strauss Street ",
                            LastName = "Foster",
                            PhoneNumber = "(248) 531-9455",
                            RegistrationDate = new DateTime(2019, 7, 10, 0, 51, 59, 326, DateTimeKind.Local).AddTicks(7413)
                        },
                        new
                        {
                            MemberId = 4,
                            BirthDate = new DateTime(1914, 11, 26, 22, 42, 44, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jadamiller@libra.ry",
                            FirstName = "Jada",
                            HomeAddress = "2804 Beverly Road ",
                            LastName = "Miller",
                            PhoneNumber = "(372) 422-3356",
                            RegistrationDate = new DateTime(2020, 6, 5, 0, 51, 59, 326, DateTimeKind.Local).AddTicks(7861)
                        },
                        new
                        {
                            MemberId = 5,
                            BirthDate = new DateTime(1919, 6, 18, 9, 53, 3, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jadetorres@libra.ry",
                            FirstName = "Jade",
                            HomeAddress = "2681 38th Street ",
                            LastName = "Torres",
                            PhoneNumber = "(498) 232-2190",
                            RegistrationDate = new DateTime(2020, 7, 2, 0, 51, 59, 326, DateTimeKind.Local).AddTicks(8418)
                        },
                        new
                        {
                            MemberId = 6,
                            BirthDate = new DateTime(1957, 10, 28, 10, 4, 36, 0, DateTimeKind.Unspecified),
                            EmailAddress = "lindseymoore@libra.ry",
                            FirstName = "Lindsey",
                            HomeAddress = "5820 Hazel Court ",
                            LastName = "Moore",
                            PhoneNumber = "(575) 379-1342",
                            RegistrationDate = new DateTime(2019, 1, 13, 0, 51, 59, 326, DateTimeKind.Local).AddTicks(8878)
                        },
                        new
                        {
                            MemberId = 7,
                            BirthDate = new DateTime(1959, 4, 8, 22, 12, 9, 0, DateTimeKind.Unspecified),
                            EmailAddress = "samanthatorres@libra.ry",
                            FirstName = "Samantha",
                            HomeAddress = "1849 Grove Street ",
                            LastName = "Torres",
                            PhoneNumber = "(720) 316-3762",
                            RegistrationDate = new DateTime(2018, 9, 5, 0, 51, 59, 326, DateTimeKind.Local).AddTicks(9366)
                        },
                        new
                        {
                            MemberId = 8,
                            BirthDate = new DateTime(2015, 10, 18, 9, 8, 20, 0, DateTimeKind.Unspecified),
                            EmailAddress = "amandafoster@libra.ry",
                            FirstName = "Amanda",
                            HomeAddress = "4106 Billings Place ",
                            LastName = "Foster",
                            PhoneNumber = "(445) 233-8906",
                            RegistrationDate = new DateTime(2020, 5, 18, 0, 51, 59, 326, DateTimeKind.Local).AddTicks(9796)
                        },
                        new
                        {
                            MemberId = 9,
                            BirthDate = new DateTime(1995, 11, 22, 11, 14, 53, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jordanroberts@libra.ry",
                            FirstName = "Jordan",
                            HomeAddress = "1475 Pierrepont Place ",
                            LastName = "Roberts",
                            PhoneNumber = "(285) 646-0359",
                            RegistrationDate = new DateTime(2019, 8, 12, 0, 51, 59, 327, DateTimeKind.Local).AddTicks(247)
                        },
                        new
                        {
                            MemberId = 10,
                            BirthDate = new DateTime(2013, 8, 18, 22, 8, 3, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jennagarcia@libra.ry",
                            FirstName = "Jenna",
                            HomeAddress = "8855 Ridgewood Place ",
                            LastName = "Garcia",
                            PhoneNumber = "(695) 311-0252",
                            RegistrationDate = new DateTime(2020, 4, 10, 0, 51, 59, 327, DateTimeKind.Local).AddTicks(732)
                        },
                        new
                        {
                            MemberId = 11,
                            BirthDate = new DateTime(1963, 2, 22, 11, 7, 7, 0, DateTimeKind.Unspecified),
                            EmailAddress = "amandarodriguez@libra.ry",
                            FirstName = "Amanda",
                            HomeAddress = "6903 Branton Street ",
                            LastName = "Rodriguez",
                            PhoneNumber = "(702) 732-0790",
                            RegistrationDate = new DateTime(2020, 11, 22, 0, 51, 59, 327, DateTimeKind.Local).AddTicks(1242)
                        },
                        new
                        {
                            MemberId = 12,
                            BirthDate = new DateTime(1921, 1, 1, 3, 11, 28, 0, DateTimeKind.Unspecified),
                            EmailAddress = "brandonmiller@libra.ry",
                            FirstName = "Brandon",
                            HomeAddress = "1493 Boynton Place ",
                            LastName = "Miller",
                            PhoneNumber = "(433) 230-6315",
                            RegistrationDate = new DateTime(2018, 6, 28, 0, 51, 59, 327, DateTimeKind.Local).AddTicks(1738)
                        },
                        new
                        {
                            MemberId = 13,
                            BirthDate = new DateTime(1936, 3, 22, 10, 36, 38, 0, DateTimeKind.Unspecified),
                            EmailAddress = "kennethmartinez@libra.ry",
                            FirstName = "Kenneth",
                            HomeAddress = "3856 Olean Street ",
                            LastName = "Martinez",
                            PhoneNumber = "(327) 336-7046",
                            RegistrationDate = new DateTime(2020, 1, 27, 0, 51, 59, 327, DateTimeKind.Local).AddTicks(2282)
                        },
                        new
                        {
                            MemberId = 14,
                            BirthDate = new DateTime(1969, 7, 3, 22, 43, 46, 0, DateTimeKind.Unspecified),
                            EmailAddress = "katiesimmons@libra.ry",
                            FirstName = "Katie",
                            HomeAddress = "692 Nolans Lane ",
                            LastName = "Simmons",
                            PhoneNumber = "(746) 742-1463",
                            RegistrationDate = new DateTime(2019, 10, 24, 0, 51, 59, 327, DateTimeKind.Local).AddTicks(2817)
                        },
                        new
                        {
                            MemberId = 15,
                            BirthDate = new DateTime(1945, 2, 3, 17, 58, 13, 0, DateTimeKind.Unspecified),
                            EmailAddress = "jacobdavis@libra.ry",
                            FirstName = "Jacob",
                            HomeAddress = "2603 Narrows Avenue ",
                            LastName = "Davis",
                            PhoneNumber = "(623) 677-9745",
                            RegistrationDate = new DateTime(2019, 5, 13, 0, 51, 59, 327, DateTimeKind.Local).AddTicks(3254)
                        },
                        new
                        {
                            MemberId = 16,
                            BirthDate = new DateTime(1931, 10, 14, 3, 56, 15, 0, DateTimeKind.Unspecified),
                            EmailAddress = "chloefoster@libra.ry",
                            FirstName = "Chloe",
                            HomeAddress = "9825 Shell Road ",
                            LastName = "Foster",
                            PhoneNumber = "(575) 605-8513",
                            RegistrationDate = new DateTime(2020, 12, 14, 0, 51, 59, 327, DateTimeKind.Local).AddTicks(3679)
                        },
                        new
                        {
                            MemberId = 17,
                            BirthDate = new DateTime(2019, 4, 8, 13, 24, 40, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ashleyphillips@libra.ry",
                            FirstName = "Ashley",
                            HomeAddress = "9944 Meserole Street ",
                            LastName = "Phillips",
                            PhoneNumber = "(572) 282-7252",
                            RegistrationDate = new DateTime(2020, 11, 22, 0, 51, 59, 327, DateTimeKind.Local).AddTicks(4077)
                        },
                        new
                        {
                            MemberId = 18,
                            BirthDate = new DateTime(1992, 10, 22, 1, 40, 14, 0, DateTimeKind.Unspecified),
                            EmailAddress = "abigaildavis@libra.ry",
                            FirstName = "Abigail",
                            HomeAddress = "4107 Delmonico Place ",
                            LastName = "Davis",
                            PhoneNumber = "(264) 511-9081",
                            RegistrationDate = new DateTime(2018, 5, 30, 0, 51, 59, 327, DateTimeKind.Local).AddTicks(4465)
                        },
                        new
                        {
                            MemberId = 19,
                            BirthDate = new DateTime(2017, 10, 13, 16, 25, 41, 0, DateTimeKind.Unspecified),
                            EmailAddress = "haleyjackson@libra.ry",
                            FirstName = "Haley",
                            HomeAddress = "2163 27th Avenue ",
                            LastName = "Jackson",
                            PhoneNumber = "(276) 367-4691",
                            RegistrationDate = new DateTime(2019, 2, 24, 0, 51, 59, 327, DateTimeKind.Local).AddTicks(4912)
                        },
                        new
                        {
                            MemberId = 20,
                            BirthDate = new DateTime(1949, 10, 31, 18, 19, 26, 0, DateTimeKind.Unspecified),
                            EmailAddress = "sierracarter@libra.ry",
                            FirstName = "Sierra",
                            HomeAddress = "5322 Marginal Street ",
                            LastName = "Carter",
                            PhoneNumber = "(329) 304-8362",
                            RegistrationDate = new DateTime(2020, 1, 20, 0, 51, 59, 327, DateTimeKind.Local).AddTicks(5364)
                        });
                });

            modelBuilder.Entity("Entities.BookTransaction", b =>
                {
                    b.HasOne("Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("IsbnId");

                    b.HasOne("Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
